'use client'
import {useEffect,useState} from 'react'

type Row={id:string;amount:number;method:string;senderPhone:string;status:string;proofMime:string|null;reviewNote:string|null;createdAt:string;reviewedAt:string|null;studentName:string;studentPhone:string;studentId:string;gradeName:string|null}

export default function AdminWalletClient({initialRows}:{initialRows:Row[]}){
 const [rows,setRows]=useState<Row[]>(initialRows); const [loading,setLoading]=useState(false); const [busy,setBusy]=useState(''); const [note,setNote]=useState<Record<string,string>>({}); const [error,setError]=useState('')
 async function load(){setLoading(true);setError('');try{const r=await fetch(`/api/admin/wallet/recharges?ts=${Date.now()}`,{cache:'no-store',headers:{'Cache-Control':'no-cache'}});const d=await r.json();if(!r.ok)throw new Error(d.error||'تعذر تحميل طلبات الشحن');setRows(d.requests||[])}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{const timer=setInterval(load,10000);return()=>clearInterval(timer)},[])
 async function act(id:string,action:'APPROVE'|'REJECT'){setBusy(id);setError('');try{const r=await fetch(`/api/admin/wallet/recharges/${id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,note:note[id]||''})});const d=await r.json();if(!r.ok)throw new Error(d.error||'تعذر تنفيذ العملية');await load()}catch(e:any){setError(e.message)}finally{setBusy('')}}
 return <>
  <div className="flex items-center justify-between gap-3 mb-7"><div><h1 className="text-3xl font-black">محفظة الطلاب</h1><p className="muted mt-2">راجع إثباتات التحويل وأضف الرصيد بعد التأكد من العملية.</p></div><button type="button" onClick={load} disabled={loading} className="btn btn-primary">{loading?'جاري التحديث...':'تحديث الطلبات'}</button></div>
  {error&&<div className="card p-4 mb-4 bg-red-50 text-red-700">{error}</div>}
  <div className="mb-4 text-sm muted">طلبات الشحن: <b>{rows.length}</b></div>
  {rows.length===0?<div className="card p-10 text-center"><div className="font-black text-lg">لا توجد طلبات شحن</div><div className="muted mt-2">سيتم تحديث القائمة تلقائيًا كل 10 ثوانٍ.</div></div>:<div className="space-y-4">{rows.map(r=><div key={r.id} className="card p-5"><div className="flex flex-col xl:flex-row gap-5"><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-black text-lg">{r.studentName}</h2><span className="badge">{r.gradeName||'بدون صف'}</span><span className="badge">{r.status==='PENDING'?'قيد المراجعة':r.status==='APPROVED'?'مقبول':'مرفوض'}</span></div><div className="muted text-sm mt-2">{r.studentPhone} • {r.amount} ج.م • {r.method}</div><div className="text-sm mt-1">الهاتف المحول منه: {r.senderPhone}</div><textarea disabled={r.status!=='PENDING'} className="w-full border rounded-xl p-3 mt-4" placeholder="ملاحظة للمراجعة (اختياري)" value={note[r.id]||''} onChange={e=>setNote({...note,[r.id]:e.target.value})}/>{r.status==='PENDING'&&<div className="flex flex-wrap gap-2 mt-3"><button disabled={busy===r.id} onClick={()=>act(r.id,'APPROVE')} className="btn btn-primary">تأكيد وإضافة الرصيد</button><button disabled={busy===r.id} onClick={()=>act(r.id,'REJECT')} className="btn btn-secondary">رفض الطلب</button></div>}</div><div className="w-full xl:w-72"><div className="text-sm font-bold mb-2">إثبات التحويل</div><a href={`/api/admin/wallet/recharges/${r.id}/proof`} target="_blank" rel="noreferrer"><img src={`/api/admin/wallet/recharges/${r.id}/proof`} alt="إثبات التحويل" className="w-full max-h-80 object-contain rounded-2xl border bg-gray-50"/></a></div></div></div>)}</div>}
 </>
}
