'use client'
import AdminShell from '@/components/AdminShell'
import {useEffect,useState} from 'react'
export default function AdminWallet(){
 const [rows,setRows]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(''); const [note,setNote]=useState<Record<string,string>>({});
 const load=()=>fetch('/api/admin/wallet/recharges',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'تعذر التحميل');setRows(d.requests||[])}).catch(e=>alert(e.message)).finally(()=>setLoading(false))
 useEffect(()=>{load()},[])
 async function act(id:string,action:'APPROVE'|'REJECT'){setBusy(id);try{const r=await fetch(`/api/admin/wallet/recharges/${id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,note:note[id]||''})});const d=await r.json();if(!r.ok)throw new Error(d.error||'تعذر تنفيذ العملية');await load()}catch(e:any){alert(e.message)}finally{setBusy('')}}
 return <AdminShell><div className="flex items-center justify-between mb-7"><div><h1 className="text-3xl font-black">محفظة الطلاب</h1><p className="muted mt-2">راجع إثباتات التحويل وأضف الرصيد بعد التأكد من العملية.</p></div></div>{loading?<div className="card p-8">جاري التحميل...</div>:<div className="space-y-4">{rows.map(r=><div key={r.id} className="card p-5"><div className="flex flex-col xl:flex-row gap-5"><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-black text-lg">{r.studentName}</h2><span className="badge">{r.gradeName||'بدون صف'}</span><span className="badge">{r.status==='PENDING'?'قيد المراجعة':r.status==='APPROVED'?'مقبول':'مرفوض'}</span></div><div className="muted text-sm mt-2">{r.studentPhone} • {r.amount} ج.م • {r.method}</div>{r.senderPhone&&<div className="text-sm mt-1">الهاتف المحول منه: {r.senderPhone}</div>}<textarea disabled={r.status!=='PENDING'} className="w-full border rounded-xl p-3 mt-4" placeholder="ملاحظة للمراجعة (اختياري)" value={note[r.id]||''} onChange={e=>setNote({...note,[r.id]:e.target.value})}/>{r.status==='PENDING'&&<div className="flex flex-wrap gap-2 mt-3"><button disabled={busy===r.id} onClick={()=>act(r.id,'APPROVE')} className="btn btn-primary">تأكيد وإضافة الرصيد</button><button disabled={busy===r.id} onClick={()=>act(r.id,'REJECT')} className="btn btn-secondary">رفض الطلب</button></div>}</div><div className="w-full xl:w-72"><div className="text-sm font-bold mb-2">إثبات التحويل</div><a href={`/api/admin/wallet/recharges/${r.id}/proof`} target="_blank" rel="noreferrer"><img src={`/api/admin/wallet/recharges/${r.id}/proof`} alt="إثبات التحويل" className="w-full max-h-80 object-contain rounded-2xl border bg-gray-50"/></a></div></div></div>)}{!rows.length&&<div className="card p-10 text-center muted">لا توجد طلبات شحن.</div>}</div>}</AdminShell>
}
