'use client'
import Link from 'next/link'; import DashboardShell from '@/components/DashboardShell'; import {useEffect,useState} from 'react'
type Lesson={id:string;title:string;course:string;subject:string;durationSec:number;watchedPct:number;completed:boolean;status:string;videoAvailable:boolean}
export default function Lessons(){
 const [lessons,setLessons]=useState<Lesson[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
 useEffect(()=>{fetch('/api/student/lessons',{cache:'no-store'}).then(async r=>{const d=await r.json(); if(!r.ok) throw new Error(d.error||'تعذر تحميل الدروس'); return d}).then(d=>setLessons(d.lessons??[])).catch(e=>setError(e.message||'تعذر تحميل الدروس')).finally(()=>setLoading(false))},[])
 return <DashboardShell title="الدروس"><div className="mb-7"><h1 className="text-3xl font-black">دروسي</h1><p className="muted mt-2">الدروس الخاصة بالكورسات المسجل فيها، مع حالة تقدمك الفعلية.</p></div>
 {loading?<div className="space-y-3">{[1,2,3].map(i=><div key={i} className="card h-24 animate-pulse bg-white"/> )}</div>:error?<div className="card p-8 text-center"><div className="text-xl font-black">حصلت مشكلة في تحميل الدروس</div><p className="muted mt-2">{error}</p></div>:lessons.length?<div className="space-y-3">{lessons.map(l=><div key={l.id} className="card p-5 flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div className="min-w-0"><div className="text-sm text-[var(--primary)] font-bold">{l.course} • {l.subject}</div><h2 className="font-black text-lg mt-1">{l.title}</h2><p className="muted text-sm mt-1">{l.durationSec?`${Math.floor(l.durationSec/60)} دقيقة`: 'المدة غير محددة'} • {l.watchedPct}% منجز</p><div className="h-2 bg-gray-100 rounded-full mt-3 overflow-hidden max-w-xl"><div className="h-full bg-[var(--primary)]" style={{width:`${Math.min(100,Math.max(0,l.watchedPct))}%`}}/></div></div><div className="flex items-center gap-3 shrink-0"><span className="badge">{l.status}</span>{l.videoAvailable&&l.status!=='مغلق'?<Link href={`/student/lessons/${l.id}`} className="btn btn-primary">{l.completed?'مشاهدة الدرس':'فتح الدرس'}</Link>:<span className="btn btn-soft opacity-70">غير متاح</span>}</div></div>)}</div>:<div className="card p-10 text-center"><div className="text-5xl">📚</div><h2 className="text-xl font-black mt-4">لسه مفيش دروس متاحة</h2><p className="muted mt-2">لما تسجل في كورس وتتوفر دروسه هتظهر هنا.</p></div>}
 </DashboardShell>
}
