'use client'
import DashboardShell from '@/components/DashboardShell'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { ArrowLeft, BookOpen, CheckCircle2, WalletCards } from 'lucide-react'
type Course={id:string;coverUrl?:string|null;title:string;grade:string;subject:string;teacher:string;lessons:number;enrolled:boolean;price:number;progress:number}
export default function Courses(){
 const [courses,setCourses]=useState<Course[]>([]),[studentGrade,setStudentGrade]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(''),[message,setMessage]=useState('')
 const load=()=>fetch('/api/courses',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'تعذر تحميل الكورسات');setStudentGrade(d.gradeName||'');setCourses(d.courses??[])}).catch(e=>setError(e.message||'تعذر تحميل الكورسات')).finally(()=>setLoading(false))
 useEffect(()=>{load()},[])
 async function purchase(id:string){setBusy(id);setError('');setMessage('');try{const r=await fetch('/api/student/wallet/purchase',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({courseId:id})});const d=await r.json();if(!r.ok)throw new Error(d.error||'تعذر الشراء');setMessage(d.message||'تم شراء الكورس بنجاح');await load()}catch(e:any){setError(e.message)}finally{setBusy('')}}
 return <DashboardShell title="الكورسات"><div className="space-y-6 pb-10">
  <section className="relative overflow-hidden rounded-[28px] bg-[linear-gradient(135deg,#32105f,#6d2fa3_58%,#8d52bd)] px-6 py-7 md:px-9 md:py-9 text-white shadow-[0_20px_55px_rgba(72,30,105,.18)]">
   <div className="absolute -left-16 -top-20 h-64 w-64 rounded-full bg-white/10 blur-2xl"/>
   <div className="relative flex flex-col md:flex-row md:items-end md:justify-between gap-6">
    <div><div className="inline-flex rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-black">مساحة التعلم</div><h1 className="mt-4 text-3xl md:text-4xl font-black">كورسات صفك</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-white/80">الكورسات هنا متوافقة تلقائيًا مع الصف المسجل في حسابك.</p></div>
    <div className="rounded-2xl border border-white/15 bg-white/10 px-5 py-4 min-w-[190px]"><div className="text-xs text-white/70">الصف الدراسي</div><div className="mt-1 text-lg font-black">{studentGrade||'جاري التحقق...'}</div></div>
   </div>
  </section>
  {message&&<div className="rounded-2xl border border-green-200 bg-green-50 px-5 py-4 text-sm font-bold text-green-700">{message}</div>}
  {error&&<div className="rounded-2xl border border-red-200 bg-red-50 px-5 py-4 text-sm font-bold text-red-700">{error}</div>}
  {loading?<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{[1,2,3].map(i=><div key={i} className="h-80 rounded-[24px] bg-gray-100 animate-pulse"/>)}</div>:courses.length?<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{courses.map(c=><article key={c.id} className="group overflow-hidden rounded-[24px] border border-[#eee8f4] bg-white shadow-[0_10px_30px_rgba(42,24,65,.06)] transition duration-200 hover:-translate-y-1">
   <div className="relative h-44 overflow-hidden bg-[linear-gradient(135deg,#f3eafa,#fff)]">{c.coverUrl?<img src={c.coverUrl} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/>:<div className="h-full grid place-items-center"><div className="grid h-20 w-20 place-items-center rounded-3xl bg-white text-3xl font-black text-[var(--primary)] shadow-sm">{c.title.slice(0,1)}</div></div>}<div className="absolute right-4 top-4 rounded-full bg-white/95 px-3 py-1.5 text-xs font-black text-[var(--primary)]">{c.grade}</div>{c.enrolled&&<div className="absolute left-4 top-4 flex items-center gap-1.5 rounded-full bg-green-600 px-3 py-1.5 text-xs font-black text-white"><CheckCircle2 size={14}/> مفتوح</div>}</div>
   <div className="p-5"><div className="text-xs font-black text-[var(--primary)]">{c.subject}</div><h2 className="mt-1 text-xl font-black leading-8">{c.title}</h2><p className="mt-2 text-sm text-[#77717e]">{c.teacher} <span className="mx-1">•</span> {c.lessons} درس</p>
   {c.enrolled?<><div className="mt-5 flex justify-between text-xs font-bold"><span>التقدم</span><span>{c.progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#eeeaf4]"><div className="h-full rounded-full bg-[var(--primary)]" style={{width:c.progress+'%'}}/></div><Link href={'/student/courses/'+c.id} className="mt-5 flex h-11 items-center justify-center gap-2 rounded-xl bg-[var(--primary)] text-sm font-black text-white">فتح الكورس <ArrowLeft size={16}/></Link></>:<><div className="mt-5 flex items-center justify-between rounded-xl bg-[#faf8fc] px-4 py-3"><span className="text-xs font-bold text-[#77717e]">سعر الكورس</span><b className="text-lg">{c.price} ج.م</b></div><button disabled={busy===c.id} onClick={()=>purchase(c.id)} className="mt-3 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[var(--primary)] text-sm font-black text-white disabled:opacity-60">{busy===c.id?'جاري الشراء...':<><WalletCards size={16}/> شراء من المحفظة</>}</button></>}</div>
  </article>)}</div>:<div className="rounded-[24px] border border-dashed border-[#ddd4e7] bg-white px-6 py-16 text-center"><BookOpen className="mx-auto text-[var(--primary)]" size={44}/><h2 className="mt-4 text-xl font-black">لا توجد كورسات منشورة لصفك حاليًا</h2><p className="mt-2 text-sm text-[#77717e]">عندما يتم نشر محتوى جديد لصفك سيظهر هنا.</p></div>}
 </div></DashboardShell>
}