'use client'
import DashboardShell from '@/components/DashboardShell'
import Link from 'next/link'
import {useEffect,useState} from 'react'
type Course={id:string;title:string;grade:string;subject:string;teacher:string;lessons:number;enrolled:boolean;price:number;progress:number}
export default function Courses(){
 const [courses,setCourses]=useState<Course[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [busy,setBusy]=useState(''); const [message,setMessage]=useState('')
 const load=()=>fetch('/api/courses',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'تعذر تحميل الكورسات');return d}).then(d=>setCourses(d.courses??[])).catch(e=>setError(e.message||'تعذر تحميل الكورسات')).finally(()=>setLoading(false))
 useEffect(()=>{load()},[])
 async function purchase(id:string){setBusy(id);setError('');setMessage('');try{const r=await fetch('/api/student/wallet/purchase',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({courseId:id})});const d=await r.json();if(!r.ok)throw new Error(d.error||'تعذر الشراء');setMessage(d.message);await load()}catch(e:any){setError(e.message)}finally{setBusy('')}}
 return <DashboardShell title="الكورسات"><div className="flex flex-col md:flex-row md:items-center justify-between gap-3 mb-7"><div><h1 className="text-3xl font-black">كورسات صفك</h1><p className="muted mt-2">كل الكورسات المنشورة لصفك فقط. افتح أي كورس من رصيد المحفظة، ويظل مفتوحًا على حسابك.</p></div><Link href="/student/wallet" className="btn btn-primary">المحفظة</Link></div>{message&&<div className="card p-4 mb-5 bg-green-50 text-green-700">{message}</div>}{error&&<div className="card p-4 mb-5 bg-red-50 text-red-700">{error}</div>}{loading?<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{[1,2,3].map(i=><div key={i} className="card h-64 animate-pulse bg-gray-50"/>)}</div>:courses.length?<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{courses.map(c=><div key={c.id} className="card overflow-hidden"><div className="h-32 bg-[linear-gradient(145deg,#f1e9f8,#fff)] flex items-center justify-center"><div className="w-16 h-16 rounded-2xl bg-[var(--primary-soft)] text-[var(--primary)] grid place-items-center text-2xl font-black">{c.title.slice(0,1)}</div></div><div className="p-5"><div className="text-sm text-[var(--primary)] font-bold">{c.grade} • {c.subject}</div><h3 className="text-xl font-black mt-1">{c.title}</h3><div className="muted text-sm mt-3">{c.teacher} • {c.lessons} درس</div>{c.enrolled?<><div className="flex justify-between text-sm mt-4"><span>التقدم</span><b>{c.progress}%</b></div><div className="h-2 bg-gray-100 rounded-full mt-2 overflow-hidden"><div className="h-full bg-[var(--primary)]" style={{width:`${c.progress}%`}}/></div><Link href={`/student/courses/${c.id}`} className="btn btn-primary w-full mt-4 text-center">فتح الكورس</Link></>:<><div className="flex justify-between text-sm mt-4"><span>السعر</span><b>{c.price} ج.م</b></div><button disabled={busy===c.id} onClick={()=>purchase(c.id)} className="btn btn-primary w-full mt-4">{busy===c.id?'جاري الشراء...':'شراء من المحفظة'}</button></>}</div></div>)}</div>:<div className="card p-10 text-center"><div className="text-5xl">📚</div><h2 className="text-xl font-black mt-4">لا توجد كورسات منشورة لصفك حاليًا</h2></div>}</DashboardShell>}
