-- Production baseline. Apply this migration to a new database before subsequent migrations.
CREATE TYPE "Role" AS ENUM ('STUDENT','PARENT','TEACHER','ADMIN','SUPPORT');
CREATE TYPE "StudyType" AS ENUM ('ONLINE','CENTER','HYBRID');
CREATE TYPE "AttendanceStatus" AS ENUM ('PRESENT','ABSENT','LATE','ONLINE');
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING','CONFIRMED','REJECTED','REFUNDED');
CREATE TYPE "OrderStatus" AS ENUM ('PENDING','CONFIRMED','CANCELLED');
CREATE TABLE "User" ("id" TEXT PRIMARY KEY,"phone" TEXT NOT NULL UNIQUE,"name" TEXT NOT NULL,"passwordHash" TEXT NOT NULL,"role" "Role" NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Governorate" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL UNIQUE);
CREATE TABLE "School" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL,"governorateId" TEXT);
CREATE TABLE "Grade" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL UNIQUE);
CREATE TABLE "Subject" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL UNIQUE);
CREATE TABLE "Student" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL UNIQUE,"gradeId" TEXT,"schoolId" TEXT,"governorateId" TEXT,"studyType" "StudyType" NOT NULL DEFAULT 'ONLINE',"guardianPhone" TEXT);
CREATE TABLE "Parent" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL UNIQUE);
CREATE TABLE "ParentStudent" ("parentId" TEXT NOT NULL,"studentId" TEXT NOT NULL,PRIMARY KEY("parentId","studentId"));
CREATE TABLE "Teacher" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL UNIQUE);
CREATE TABLE "Course" ("id" TEXT PRIMARY KEY,"title" TEXT NOT NULL,"description" TEXT,"price" DOUBLE PRECISION NOT NULL DEFAULT 0,"published" BOOLEAN NOT NULL DEFAULT false,"gradeId" TEXT NOT NULL,"subjectId" TEXT NOT NULL,"teacherId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "CourseEnrollment" ("studentId" TEXT NOT NULL,"courseId" TEXT NOT NULL,"enrolledAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY("studentId","courseId"));
CREATE TABLE "CourseModule" ("id" TEXT PRIMARY KEY,"title" TEXT NOT NULL,"order" INTEGER NOT NULL,"courseId" TEXT NOT NULL);
CREATE TABLE "Video" ("id" TEXT PRIMARY KEY,"provider" TEXT NOT NULL DEFAULT 'YOUTUBE',"providerAssetId" TEXT,"youtubeUrl" TEXT,"durationSec" INTEGER,"isPublished" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Lesson" ("id" TEXT PRIMARY KEY,"title" TEXT NOT NULL,"order" INTEGER NOT NULL,"moduleId" TEXT NOT NULL,"videoId" TEXT UNIQUE);
CREATE TABLE "LessonResource" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL,"url" TEXT NOT NULL,"lessonId" TEXT NOT NULL);
CREATE TABLE "Book" ("id" TEXT PRIMARY KEY,"title" TEXT NOT NULL,"gradeId" TEXT,"subjectId" TEXT,"fileUrl" TEXT);
CREATE TABLE "Exam" ("id" TEXT PRIMARY KEY,"title" TEXT NOT NULL,"durationMin" INTEGER,"courseId" TEXT);
CREATE TABLE "Question" ("id" TEXT PRIMARY KEY,"text" TEXT NOT NULL,"type" TEXT NOT NULL,"points" INTEGER NOT NULL DEFAULT 1,"examId" TEXT NOT NULL);
CREATE TABLE "QuestionOption" ("id" TEXT PRIMARY KEY,"text" TEXT NOT NULL,"isCorrect" BOOLEAN NOT NULL,"questionId" TEXT NOT NULL);
CREATE TABLE "ExamAttempt" ("id" TEXT PRIMARY KEY,"studentId" TEXT NOT NULL,"examId" TEXT NOT NULL,"startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"submittedAt" TIMESTAMP(3),"score" DOUBLE PRECISION);
CREATE TABLE "ExamAnswer" ("id" TEXT PRIMARY KEY,"attemptId" TEXT NOT NULL,"questionId" TEXT NOT NULL,"answerText" TEXT,"selectedOptionId" TEXT,"isCorrect" BOOLEAN,UNIQUE("attemptId","questionId"));
CREATE TABLE "Assignment" ("id" TEXT PRIMARY KEY,"title" TEXT NOT NULL,"description" TEXT,"dueAt" TIMESTAMP(3) NOT NULL,"courseId" TEXT);
CREATE TABLE "AssignmentSubmission" ("id" TEXT PRIMARY KEY,"assignmentId" TEXT NOT NULL,"studentId" TEXT NOT NULL,"submittedAt" TIMESTAMP(3),"fileUrl" TEXT,"score" DOUBLE PRECISION,"feedback" TEXT,UNIQUE("assignmentId","studentId"));
CREATE TABLE "StudentProgress" ("id" TEXT PRIMARY KEY,"studentId" TEXT NOT NULL,"lessonId" TEXT NOT NULL,"watchedPct" DOUBLE PRECISION NOT NULL DEFAULT 0,"completed" BOOLEAN NOT NULL DEFAULT false,"lastPositionSec" INTEGER NOT NULL DEFAULT 0,UNIQUE("studentId","lessonId"));
CREATE TABLE "Center" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL,"address" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "CenterGroup" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL,"centerId" TEXT NOT NULL);
CREATE TABLE "Schedule" ("id" TEXT PRIMARY KEY,"centerId" TEXT NOT NULL,"groupId" TEXT,"teacherId" TEXT,"dayOfWeek" INTEGER NOT NULL,"startTime" TEXT NOT NULL,"endTime" TEXT NOT NULL);
CREATE TABLE "Attendance" ("id" TEXT PRIMARY KEY,"studentId" TEXT NOT NULL,"status" "AttendanceStatus" NOT NULL,"date" TIMESTAMP(3) NOT NULL,"centerId" TEXT,"groupId" TEXT,"scheduleId" TEXT);
CREATE TABLE "StudentGrade" ("id" TEXT PRIMARY KEY,"studentId" TEXT NOT NULL,"subjectId" TEXT,"gradeId" TEXT,"title" TEXT NOT NULL,"score" DOUBLE PRECISION NOT NULL,"maxScore" DOUBLE PRECISION NOT NULL,"recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Notification" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"title" TEXT NOT NULL,"body" TEXT NOT NULL,"readAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Order" ("id" TEXT PRIMARY KEY,"studentId" TEXT NOT NULL,"courseId" TEXT NOT NULL,"amount" DOUBLE PRECISION NOT NULL,"subtotal" DOUBLE PRECISION NOT NULL,"discount" DOUBLE PRECISION NOT NULL DEFAULT 0,"couponCode" TEXT,"status" "OrderStatus" NOT NULL DEFAULT 'PENDING',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Payment" ("id" TEXT PRIMARY KEY,"orderId" TEXT NOT NULL,"status" "PaymentStatus" NOT NULL DEFAULT 'PENDING',"method" TEXT,"reference" TEXT,"notes" TEXT,"confirmedAt" TIMESTAMP(3),"confirmedById" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "YoutubeConnection" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL UNIQUE,"channelId" TEXT,"channelTitle" TEXT,"refreshToken" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Coupon" ("id" TEXT PRIMARY KEY,"code" TEXT NOT NULL UNIQUE,"type" TEXT NOT NULL,"value" DOUBLE PRECISION NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"startsAt" TIMESTAMP(3),"endsAt" TIMESTAMP(3),"usageLimit" INTEGER,"usedCount" INTEGER NOT NULL DEFAULT 0,"courseId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "SupportConversation" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'OPEN',"assignedToId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "SupportMessage" ("id" TEXT PRIMARY KEY,"conversationId" TEXT NOT NULL,"senderId" TEXT NOT NULL,"body" TEXT NOT NULL,"attachmentUrl" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Subscription" ("id" TEXT PRIMARY KEY,"studentId" TEXT NOT NULL,"courseId" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'ACTIVE',"startsAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"endsAt" TIMESTAMP(3),"externalRef" TEXT,UNIQUE("studentId","courseId"));
CREATE TABLE "Invoice" ("id" TEXT PRIMARY KEY,"orderId" TEXT NOT NULL UNIQUE,"number" TEXT NOT NULL UNIQUE,"amount" DOUBLE PRECISION NOT NULL,"currency" TEXT NOT NULL DEFAULT 'EGP',"issuedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "AuditLog" ("id" TEXT PRIMARY KEY,"actorId" TEXT,"action" TEXT NOT NULL,"entity" TEXT NOT NULL,"entityId" TEXT,"metadata" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "UploadedFile" ("id" TEXT PRIMARY KEY,"ownerId" TEXT NOT NULL,"mimeType" TEXT NOT NULL,"size" INTEGER NOT NULL,"storageKey" TEXT NOT NULL,"url" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "Course_gradeId_subjectId_idx" ON "Course"("gradeId","subjectId");
CREATE INDEX "CourseModule_courseId_order_idx" ON "CourseModule"("courseId","order");
CREATE INDEX "Lesson_moduleId_order_idx" ON "Lesson"("moduleId","order");
CREATE INDEX "ExamAttempt_studentId_examId_idx" ON "ExamAttempt"("studentId","examId");
CREATE INDEX "StudentProgress_studentId_lessonId_idx" ON "StudentProgress"("studentId","lessonId");
CREATE INDEX "CenterGroup_centerId_idx" ON "CenterGroup"("centerId");
CREATE INDEX "Schedule_centerId_dayOfWeek_idx" ON "Schedule"("centerId","dayOfWeek");
CREATE INDEX "Attendance_studentId_date_idx" ON "Attendance"("studentId","date");
CREATE INDEX "StudentGrade_studentId_recordedAt_idx" ON "StudentGrade"("studentId","recordedAt");
CREATE INDEX "Notification_userId_createdAt_idx" ON "Notification"("userId","createdAt");
CREATE INDEX "Order_studentId_status_idx" ON "Order"("studentId","status");
CREATE INDEX "Order_courseId_status_idx" ON "Order"("courseId","status");
CREATE INDEX "Payment_status_createdAt_idx" ON "Payment"("status","createdAt");
CREATE INDEX "Coupon_active_endsAt_idx" ON "Coupon"("active","endsAt");
CREATE INDEX "SupportConversation_userId_status_idx" ON "SupportConversation"("userId","status");
CREATE INDEX "SupportMessage_conversationId_createdAt_idx" ON "SupportMessage"("conversationId","createdAt");
CREATE INDEX "Subscription_studentId_status_idx" ON "Subscription"("studentId","status");
CREATE INDEX "AuditLog_entity_entityId_createdAt_idx" ON "AuditLog"("entity","entityId","createdAt");
CREATE INDEX "UploadedFile_ownerId_createdAt_idx" ON "UploadedFile"("ownerId","createdAt");
ALTER TABLE "School" ADD CONSTRAINT "School_governorateId_fkey" FOREIGN KEY("governorateId") REFERENCES "Governorate"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Student" ADD CONSTRAINT "Student_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Student" ADD CONSTRAINT "Student_gradeId_fkey" FOREIGN KEY("gradeId") REFERENCES "Grade"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Student" ADD CONSTRAINT "Student_schoolId_fkey" FOREIGN KEY("schoolId") REFERENCES "School"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Student" ADD CONSTRAINT "Student_governorateId_fkey" FOREIGN KEY("governorateId") REFERENCES "Governorate"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Parent" ADD CONSTRAINT "Parent_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ParentStudent" ADD CONSTRAINT "ParentStudent_parentId_fkey" FOREIGN KEY("parentId") REFERENCES "Parent"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ParentStudent" ADD CONSTRAINT "ParentStudent_studentId_fkey" FOREIGN KEY("studentId") REFERENCES "Student"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Teacher" ADD CONSTRAINT "Teacher_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Course" ADD CONSTRAINT "Course_gradeId_fkey" FOREIGN KEY("gradeId") REFERENCES "Grade"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Course" ADD CONSTRAINT "Course_subjectId_fkey" FOREIGN KEY("subjectId") REFERENCES "Subject"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Course" ADD CONSTRAINT "Course_teacherId_fkey" FOREIGN KEY("teacherId") REFERENCES "Teacher"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CourseEnrollment" ADD CONSTRAINT "CourseEnrollment_studentId_fkey" FOREIGN KEY("studentId") REFERENCES "Student"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CourseEnrollment" ADD CONSTRAINT "CourseEnrollment_courseId_fkey" FOREIGN KEY("courseId") REFERENCES "Course"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CourseModule" ADD CONSTRAINT "CourseModule_courseId_fkey" FOREIGN KEY("courseId") REFERENCES "Course"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Lesson" ADD CONSTRAINT "Lesson_moduleId_fkey" FOREIGN KEY("moduleId") REFERENCES "CourseModule"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Lesson" ADD CONSTRAINT "Lesson_videoId_fkey" FOREIGN KEY("videoId") REFERENCES "Video"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "LessonResource" ADD CONSTRAINT "LessonResource_lessonId_fkey" FOREIGN KEY("lessonId") REFERENCES "Lesson"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Book" ADD CONSTRAINT "Book_gradeId_fkey" FOREIGN KEY("gradeId") REFERENCES "Grade"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Book" ADD CONSTRAINT "Book_subjectId_fkey" FOREIGN KEY("subjectId") REFERENCES "Subject"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Exam" ADD CONSTRAINT "Exam_courseId_fkey" FOREIGN KEY("courseId") REFERENCES "Course"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Question" ADD CONSTRAINT "Question_examId_fkey" FOREIGN KEY("examId") REFERENCES "Exam"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "QuestionOption" ADD CONSTRAINT "QuestionOption_questionId_fkey" FOREIGN KEY("questionId") REFERENCES "Question"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ExamAttempt" ADD CONSTRAINT "ExamAttempt_studentId_fkey" FOREIGN KEY("studentId") REFERENCES "Student"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ExamAttempt" ADD CONSTRAINT "ExamAttempt_examId_fkey" FOREIGN KEY("examId") REFERENCES "Exam"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ExamAnswer" ADD CONSTRAINT "ExamAnswer_attemptId_fkey" FOREIGN KEY("attemptId") REFERENCES "ExamAttempt"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ExamAnswer" ADD CONSTRAINT "ExamAnswer_questionId_fkey" FOREIGN KEY("questionId") REFERENCES "Question"("id") ON UPDATE CASCADE;
ALTER TABLE "ExamAnswer" ADD CONSTRAINT "ExamAnswer_selectedOptionId_fkey" FOREIGN KEY("selectedOptionId") REFERENCES "QuestionOption"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Assignment" ADD CONSTRAINT "Assignment_courseId_fkey" FOREIGN KEY("courseId") REFERENCES "Course"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AssignmentSubmission" ADD CONSTRAINT "AssignmentSubmission_assignmentId_fkey" FOREIGN KEY("assignmentId") REFERENCES "Assignment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AssignmentSubmission" ADD CONSTRAINT "AssignmentSubmission_studentId_fkey" FOREIGN KEY("studentId") REFERENCES "Student"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "StudentProgress" ADD CONSTRAINT "StudentProgress_studentId_fkey" FOREIGN KEY("studentId") REFERENCES "Student"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "StudentProgress" ADD CONSTRAINT "StudentProgress_lessonId_fkey" FOREIGN KEY("lessonId") REFERENCES "Lesson"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CenterGroup" ADD CONSTRAINT "CenterGroup_centerId_fkey" FOREIGN KEY("centerId") REFERENCES "Center"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Schedule" ADD CONSTRAINT "Schedule_centerId_fkey" FOREIGN KEY("centerId") REFERENCES "Center"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Schedule" ADD CONSTRAINT "Schedule_groupId_fkey" FOREIGN KEY("groupId") REFERENCES "CenterGroup"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Schedule" ADD CONSTRAINT "Schedule_teacherId_fkey" FOREIGN KEY("teacherId") REFERENCES "Teacher"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Attendance" ADD CONSTRAINT "Attendance_studentId_fkey" FOREIGN KEY("studentId") REFERENCES "Student"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Attendance" ADD CONSTRAINT "Attendance_centerId_fkey" FOREIGN KEY("centerId") REFERENCES "Center"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Attendance" ADD CONSTRAINT "Attendance_groupId_fkey" FOREIGN KEY("groupId") REFERENCES "CenterGroup"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Attendance" ADD CONSTRAINT "Attendance_scheduleId_fkey" FOREIGN KEY("scheduleId") REFERENCES "Schedule"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "StudentGrade" ADD CONSTRAINT "StudentGrade_studentId_fkey" FOREIGN KEY("studentId") REFERENCES "Student"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "StudentGrade" ADD CONSTRAINT "StudentGrade_subjectId_fkey" FOREIGN KEY("subjectId") REFERENCES "Subject"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "StudentGrade" ADD CONSTRAINT "StudentGrade_gradeId_fkey" FOREIGN KEY("gradeId") REFERENCES "Grade"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Order" ADD CONSTRAINT "Order_studentId_fkey" FOREIGN KEY("studentId") REFERENCES "Student"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Order" ADD CONSTRAINT "Order_courseId_fkey" FOREIGN KEY("courseId") REFERENCES "Course"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Order" ADD CONSTRAINT "Order_couponCode_fkey" FOREIGN KEY("couponCode") REFERENCES "Coupon"("code") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_orderId_fkey" FOREIGN KEY("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_confirmedById_fkey" FOREIGN KEY("confirmedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "YoutubeConnection" ADD CONSTRAINT "YoutubeConnection_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Coupon" ADD CONSTRAINT "Coupon_courseId_fkey" FOREIGN KEY("courseId") REFERENCES "Course"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SupportConversation" ADD CONSTRAINT "SupportConversation_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SupportConversation" ADD CONSTRAINT "SupportConversation_assignedToId_fkey" FOREIGN KEY("assignedToId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SupportMessage" ADD CONSTRAINT "SupportMessage_conversationId_fkey" FOREIGN KEY("conversationId") REFERENCES "SupportConversation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SupportMessage" ADD CONSTRAINT "SupportMessage_senderId_fkey" FOREIGN KEY("senderId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Subscription" ADD CONSTRAINT "Subscription_studentId_fkey" FOREIGN KEY("studentId") REFERENCES "Student"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Subscription" ADD CONSTRAINT "Subscription_courseId_fkey" FOREIGN KEY("courseId") REFERENCES "Course"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_orderId_fkey" FOREIGN KEY("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_actorId_fkey" FOREIGN KEY("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "UploadedFile" ADD CONSTRAINT "UploadedFile_ownerId_fkey" FOREIGN KEY("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
