import {NextResponse} from 'next/server'
import {requireRole} from '@/lib/auth'
import {db} from '@/lib/db'
import {getYoutubeOAuthClient} from '@/lib/youtube'
import {google} from 'googleapis'
import fs from 'node:fs/promises'
import { decryptSecretOrPlain } from '@/lib/secretbox'
import os from 'node:os'
import path from 'node:path'
export const runtime='nodejs'
export const maxDuration=300
export async function POST(req:Request){let temp='';try{const admin=await requireRole(['ADMIN']);const form=await req.formData();const lessonId=String(form.get('lessonId')||'');const title=String(form.get('title')||'');const description=String(form.get('description')||'');const privacy=String(form.get('privacy')||'unlisted') as 'private'|'unlisted'|'public';const file=form.get('file');const MAX=512*1024*1024;const allowed=new Set(['video/mp4','video/webm','video/quicktime','video/x-matroska']);if(!lessonId||!title||!(file instanceof File))return NextResponse.json({error:'بيانات الفيديو ناقصة'},{status:400});if(file.size<=0||file.size>MAX||!allowed.has(file.type))return NextResponse.json({error:'صيغة أو حجم الفيديو غير مسموح'},{status:400});const lesson=await db.lesson.findUnique({where:{id:lessonId},include:{module:{include:{course:true}}}});if(!lesson)return NextResponse.json({error:'الدرس غير موجود'},{status:404});const connection=await db.youtubeConnection.findUnique({where:{userId:admin.id}});if(!connection)return NextResponse.json({error:'اربط قناة YouTube أولًا من الإعدادات'},{status:400});const client=getYoutubeOAuthClient();client.setCredentials({refresh_token:decryptSecretOrPlain(connection.refreshToken)});const youtube=google.youtube({version:'v3',auth:client});temp=path.join(os.tmpdir(),`taallum-${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`);const {Readable}=await import('node:stream');await new Promise<void>((resolve,reject)=>{const out=require('node:fs').createWriteStream(temp);Readable.fromWeb(file.stream() as any).pipe(out).on('finish',resolve).on('error',reject)});const result=await youtube.videos.insert({part:['snippet','status'],requestBody:{snippet:{title,description,categoryId:'27',defaultLanguage:'ar'},status:{privacyStatus:privacy,selfDeclaredMadeForKids:false}},media:{body:(await import('fs')).createReadStream(temp)}});const item=result.data;const videoId=item.id;if(!videoId)throw new Error('YOUTUBE_UPLOAD_FAILED');const video=await db.video.create({data:{provider:'YOUTUBE',providerAssetId:videoId,youtubeUrl:`https://www.youtube.com/watch?v=${videoId}`,isPublished:privacy!=='private'}});await db.lesson.update({where:{id:lessonId},data:{videoId:video.id}});return NextResponse.json({ok:true,videoId})}catch(e:any){const msg=e?.message==='YOUTUBE_ENV_MISSING'?'إعدادات YouTube غير مكتملة':e?.message==='YOUTUBE_UPLOAD_FAILED'?'فشل رفع الفيديو إلى YouTube':'تعذر رفع الفيديو. تأكد من اتصال القناة وحجم الملف وصلاحيات Google';return NextResponse.json({error:msg},{status:400})}finally{if(temp)await fs.rm(temp,{force:true}).catch(()=>{})}}
