import Link from 'next/link'

type IconName = 'book' | 'cap' | 'headset' | 'video' | 'chart' | 'target' | 'users' | 'heart' | 'document' | 'check'

function Icon({name}:{name:IconName}) {
  const common={width:28,height:28,viewBox:'0 0 32 32',fill:'none',stroke:'currentColor',strokeWidth:1.9,strokeLinecap:'round' as const,strokeLinejoin:'round' as const}
  if(name==='cap') return <svg {...common}><path d="M3.5 12.2 16 5l12.5 7.2L16 19.4 3.5 12.2Z"/><path d="M8 15.1v6.2c4.8 3.1 11.2 3.1 16 0v-6.2"/><path d="M28.5 12.2v7.2"/></svg>
  if(name==='book') return <svg {...common}><path d="M5 6.5c4.3-1.4 7.7-.7 11 1.7v18c-3.3-2.4-6.7-3.1-11-1.7v-18Z"/><path d="M27 6.5c-4.3-1.4-7.7-.7-11 1.7v18c3.3-2.4 6.7-3.1 11-1.7v-18Z"/><path d="M16 8.2v18"/></svg>
  if(name==='headset') return <svg {...common}><path d="M5 18v-3a11 11 0 0 1 22 0v3"/><path d="M5 18h4v8H6.5A1.5 1.5 0 0 1 5 24.5V18Z"/><path d="M27 18h-4v8h2.5a1.5 1.5 0 0 0 1.5-1.5V18Z"/><path d="M23 27c-1.8 1.2-4.1 1.8-7 1.8"/></svg>
  if(name==='video') return <svg {...common}><rect x="4" y="6" width="24" height="20" rx="4"/><path d="m13 11 8 5-8 5v-10Z"/></svg>
  if(name==='chart') return <svg {...common}><path d="M6 25V17"/><path d="M13 25V12"/><path d="M20 25V7"/><path d="M27 25V4"/><path d="M4 27h25"/></svg>
  if(name==='target') return <svg {...common}><circle cx="16" cy="16" r="11"/><circle cx="16" cy="16" r="6"/><circle cx="16" cy="16" r="1.5"/><path d="m22.5 9.5 5-5"/><path d="M23 4h4.5v4.5"/></svg>
  if(name==='users') return <svg {...common}><circle cx="16" cy="10" r="4"/><path d="M8 27v-2a8 8 0 0 1 16 0v2"/><path d="M7 15a4 4 0 0 0-4 4v2"/><path d="M25 15a4 4 0 0 1 4 4v2"/></svg>
  if(name==='heart') return <svg {...common}><path d="M16 27S5 20.5 5 12.7C5 9 7.6 6.5 11 6.5c2.2 0 4 1.1 5 2.7 1-1.6 2.8-2.7 5-2.7 3.4 0 6 2.5 6 6.2C27 20.5 16 27 16 27Z"/></svg>
  if(name==='check') return <svg {...common}><rect x="5" y="4" width="22" height="24" rx="4"/><path d="m10 16 4 4 8-9"/></svg>
  return <svg {...common}><path d="M8 5h16v22H8z"/><path d="M11 10h10M11 15h10M11 20h7"/></svg>
}

const grades = [
  { title:'الصف الأول الثانوي', label:'الصف الأول', tone:'purple', icon:'book' as IconName },
  { title:'الصف الثاني الثانوي', label:'الصف الثاني', tone:'blue', icon:'book' as IconName },
  { title:'الصف الثالث الثانوي', label:'الصف الثالث', tone:'violet', icon:'cap' as IconName },
]

const features = [
  ['target','متابعة التقدم','اعرف مستواك وشوف إنجازك أول بأول'],
  ['check','اختبارات دورية','اختبر نفسك وراجع أخطاءك باستمرار'],
  ['video','شرح احترافي','فيديوهات منظمة ومحتوى تعليمي واضح'],
  ['book','كتب وملخصات','كل المواد والمراجعات في مكان واحد'],
  ['chart','تقارير أداء','تابع درجاتك ونقاط القوة والتحسين'],
  ['headset','دعم مستمر','مساعدة وإجابة على استفساراتك وقت الحاجة'],
] as const

const uiStyles = `
.brand-lockup{display:flex;align-items:center;direction:rtl}.brand-logo{width:58px;height:58px;flex:0 0 58px;display:block;object-fit:contain;border-radius:15px;box-shadow:0 5px 16px rgba(44,20,72,.14);border:1px solid rgba(109,47,163,.12)}
.site-header{height:78px;background:rgba(255,255,255,.97);border:0;position:sticky;top:0;z-index:50;backdrop-filter:blur(16px);box-shadow:0 5px 18px rgba(38,25,57,.08)}.site-header-inner{width:min(1360px,calc(100% - 48px));gap:25px}.header-brand{width:180px}.main-nav{gap:30px}.header-actions{width:250px}.header-login{border:0;background:transparent}.header-register{background:#6d2fa3;border-radius:999px;padding-inline:22px}
.hero-section{overflow:hidden;background:radial-gradient(circle at 18% 45%,#f2e9ff 0,#fff 38%,#fff 100%);min-height:600px;position:relative}.hero-section:before{content:"";position:absolute;width:420px;height:420px;left:-180px;top:100px;border-radius:50%;background:#f5edff;filter:blur(2px);opacity:.8}.hero-inner{width:min(1360px,calc(100% - 48px));min-height:600px;grid-template-columns:1.05fr .95fr;gap:10px}.hero-copy{padding:65px 0 45px 30px}.hero-badge{background:#f0e7fb;color:#5c258e;border:1px solid #e2d1f4;padding:9px 18px;margin-bottom:18px}.hero-copy h1{font-size:64px;line-height:1.08;letter-spacing:-2.3px}.hero-copy h1 span{background:linear-gradient(90deg,#6d2fa3,#a15ee5);-webkit-background-clip:text;background-clip:text;color:transparent}.hero-copy p{font-size:18px;line-height:2;max-width:620px;color:#666070}.hero-buttons{margin-top:28px}.hero-primary{border-radius:14px;min-width:155px}.hero-secondary{border-radius:14px;min-width:165px}.hero-trust{margin-top:28px;gap:36px}.hero-visual{height:600px;justify-content:center;overflow:visible}.hero-art{width:860px;max-width:108%;height:auto;aspect-ratio:2048/758;object-fit:contain;object-position:center;filter:drop-shadow(0 24px 38px rgba(62,26,92,.15));animation:heroFloat 5s ease-in-out infinite}
.stages-section{padding:70px 0 75px;background:linear-gradient(180deg,#fff 0%,#fbf8ff 100%)}.stages-inner{width:min(1240px,calc(100% - 48px));display:block;background:transparent;border:0;box-shadow:none;padding:0}.stages-heading{text-align:center;margin-bottom:42px}.stages-heading>span{background:#f0e7fb;color:#6d2fa3;padding:9px 19px}.stages-heading h2{font-size:44px;color:#27213a;margin:16px 0 7px}.stages-heading p{font-size:16px;color:#7a7484}.grade-cards{grid-template-columns:repeat(3,1fr);gap:28px}.grade-card{height:390px;display:flex;flex-direction:column;align-items:stretch;justify-content:flex-end;padding:0;overflow:hidden;border:1px solid #ece7f2;border-radius:24px;background:#fff;box-shadow:0 13px 30px rgba(43,25,63,.09)}.grade-card:hover{transform:translateY(-8px);box-shadow:0 20px 40px rgba(109,47,163,.16)}.grade-cover{position:absolute;inset:0 0 auto;height:215px;overflow:hidden}.grade-cover:after{content:"";position:absolute;inset:0;background:linear-gradient(135deg,rgba(109,47,163,.88),rgba(35,18,64,.15))}.grade-card.tone-blue .grade-cover:after{background:linear-gradient(135deg,rgba(36,119,211,.88),rgba(24,47,93,.18))}.grade-card.tone-violet .grade-cover:after{background:linear-gradient(135deg,rgba(132,70,205,.9),rgba(40,18,73,.2))}.grade-cover img{width:100%;height:100%;object-fit:cover;object-position:center}.grade-cover-label{position:absolute;z-index:2;top:18px;right:18px;background:rgba(255,255,255,.94);color:#3b245d;border-radius:999px;padding:7px 12px;font-size:12px;font-weight:900}.grade-card-body{position:relative;z-index:3;background:#fff;padding:22px 23px 20px;min-height:185px;text-align:right}.grade-icon{width:48px;height:48px;border-radius:14px;background:#f4edfc;color:#6d2fa3;display:grid;place-items:center;position:absolute;right:22px;top:-24px;border:5px solid #fff;box-shadow:0 5px 15px rgba(45,25,65,.08)}.grade-card h3{font-size:25px;line-height:1.3;color:#292238;margin:0 0 8px;font-weight:950}.grade-card p{font-size:13px;color:#777080;margin:0 0 17px}.grade-card>b{position:static;width:100%;height:45px;border-radius:12px;background:#6d2fa3;color:#fff;display:flex;align-items:center;justify-content:center;font-size:14px;font-weight:900}
.platform-story{width:min(1240px,calc(100% - 48px));margin:0 auto;padding:35px 0 70px}.platform-story-inner{min-height:510px;display:grid;grid-template-columns:1.02fr .98fr;align-items:center;gap:75px;direction:ltr}.platform-story-visual{position:relative;height:510px;display:flex;align-items:center;justify-content:center}.platform-story-visual:before{content:"";position:absolute;width:430px;height:430px;border-radius:50%;background:#f2e8fb;filter:blur(1px);z-index:0}.platform-story-image{width:470px;height:470px;object-fit:cover;object-position:center;border-radius:34px;position:relative;z-index:1;box-shadow:0 24px 55px rgba(68,27,101,.18);animation:storyFloat 6s ease-in-out infinite}.platform-story-card{position:absolute;z-index:3;right:4px;top:54px;background:#fff;border:1px solid #eee5f7;border-radius:20px;padding:13px 18px;display:flex;align-items:center;gap:12px;box-shadow:0 14px 32px rgba(55,26,82,.12);direction:rtl}.platform-story-card-icon{width:48px;height:48px;border-radius:15px;background:#f0e7fb;color:#6d2fa3;display:grid;place-items:center}.platform-story-card strong{font-size:15px;color:#30233d;white-space:nowrap}.platform-story-card small{display:block;color:#8a8192;font-size:10px;margin-top:3px}.platform-story-copy{direction:rtl;text-align:right;padding:0 5px}.platform-story-badge{display:inline-flex;align-items:center;gap:7px;border:1px solid #dcc9ef;background:#f7f1fc;color:#6d2fa3;border-radius:999px;padding:9px 17px;font-size:13px;font-weight:950}.platform-story-copy h2{font-size:48px;line-height:1.16;color:#292238;margin:18px 0 13px;font-weight:950;letter-spacing:-1.2px}.platform-story-copy h2 span{color:#6d2fa3}.platform-story-copy p{font-size:16px;line-height:2;color:#6f6878;margin:0;max-width:590px;font-weight:650}.story-points{display:grid;grid-template-columns:repeat(2,1fr);gap:12px 18px;margin:24px 0}.story-point{display:flex;align-items:center;gap:9px;color:#3b3147;font-size:13px;font-weight:900}.story-point i{width:30px;height:30px;border-radius:10px;background:#f2eafa;color:#6d2fa3;display:grid;place-items:center;font-style:normal}.story-actions{display:flex;align-items:center;gap:12px;margin-top:20px}.story-primary,.story-secondary{height:48px;border-radius:13px;padding:0 22px;display:inline-flex;align-items:center;justify-content:center;font-weight:950}.story-primary{background:#6d2fa3;color:#fff;box-shadow:0 10px 22px rgba(109,47,163,.2)}.story-secondary{border:1px solid #e3dce9;background:#fff;color:#3c3048}.story-secondary span{margin-right:7px;color:#6d2fa3}.stats-strip{width:min(1240px,calc(100% - 48px));margin:-25px auto 0;padding:17px 8px;border:1px solid #eee8f5;border-radius:22px;background:#fff;box-shadow:0 10px 28px rgba(45,25,65,.07);position:relative;z-index:5}.stats-strip>div{padding:6px 25px}.stats-strip strong{font-size:25px}.stats-strip em{background:#f3eafb;color:#6d2fa3}
.why-section{width:min(1240px,calc(100% - 48px));padding:85px 0 75px}.why-heading{text-align:center;margin-bottom:42px}.why-heading h2{font-size:42px;color:#292238}.why-heading h2 span{color:#6d2fa3}.why-heading p{font-size:16px}.features-grid{grid-template-columns:repeat(3,1fr);gap:22px}.feature-card{min-height:175px;border-radius:22px;padding:24px 22px;transition:.25s}.feature-card:hover{transform:translateY(-5px);box-shadow:0 16px 32px rgba(109,47,163,.1)}.feature-icon{width:54px;height:54px;border-radius:16px;background:#f4eafe;color:#6d2fa3;margin-bottom:18px}.feature-card h3{font-size:19px;margin-bottom:7px}.feature-card p{font-size:13px;line-height:1.7}
.bottom-cta{width:min(1240px,calc(100% - 48px));margin:0 auto 35px;min-height:150px;border-radius:25px;background:linear-gradient(105deg,#32105f,#6d2fa3 65%,#8b4dc0);grid-template-columns:150px 1fr 190px;gap:25px;padding:20px 30px}.cta-brand img{width:120px;height:70px}.cta-copy{text-align:right}.cta-copy strong{font-size:25px}.cta-copy span{font-size:13px}.cta-button{border-radius:14px;height:54px}.cta-side{display:none}.site-footer{width:min(1240px,calc(100% - 48px));padding:20px 0 28px;border-top:1px solid #eee8f4}
@keyframes heroFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-7px)}}@keyframes storyFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-6px)}}
@media(max-width:1100px){.hero-copy h1{font-size:49px}.hero-visual{height:520px}.hero-section,.hero-inner{min-height:520px}.hero-art{width:760px;max-width:115%}.main-nav{gap:16px;font-size:13px}.header-brand{width:120px}.features-grid{grid-template-columns:repeat(2,1fr)}.platform-story-inner{gap:35px}.platform-story-copy h2{font-size:40px}.platform-story-image{width:390px;height:390px}.platform-story-visual{height:440px}}
@media(max-width:760px){.site-header{height:66px}.site-header-inner{width:calc(100% - 24px)}.main-nav{display:none}.header-brand{width:auto}.header-brand .brand-logo{width:48px;height:48px;flex-basis:48px}.header-actions{width:auto;gap:5px}.header-login{display:none}.header-register{height:38px;padding:0 15px;font-size:11px}.hero-section{min-height:auto}.hero-inner{width:calc(100% - 24px);grid-template-columns:1fr;min-height:auto}.hero-visual{order:1;height:300px}.hero-art{width:100%;max-width:600px;height:300px}.hero-copy{order:2;text-align:center;padding:20px 0 45px}.hero-copy h1{font-size:42px}.hero-copy p{font-size:15px}.hero-buttons{justify-content:center}.hero-trust{justify-content:center}.stages-section{padding:50px 0 60px}.stages-inner{width:calc(100% - 24px)}.stages-heading h2{font-size:34px}.grade-cards{grid-template-columns:1fr;gap:20px}.grade-card{height:350px}.platform-story{width:calc(100% - 24px);padding:25px 0 55px}.platform-story-inner{grid-template-columns:1fr;gap:28px;direction:rtl}.platform-story-visual{height:350px;order:1}.platform-story-image{width:310px;height:310px;border-radius:25px}.platform-story-visual:before{width:300px;height:300px}.platform-story-card{right:calc(50% - 145px);top:14px}.platform-story-copy{order:2;text-align:center}.platform-story-copy h2{font-size:34px}.platform-story-copy p{font-size:14px}.story-points{grid-template-columns:1fr 1fr;text-align:right}.story-actions{justify-content:center}.stats-strip{width:calc(100% - 24px);grid-template-columns:repeat(2,1fr)}.stats-strip>div{padding:8px 13px}.why-section{width:calc(100% - 24px);padding:60px 0}.why-heading h2{font-size:34px}.features-grid{grid-template-columns:1fr}.bottom-cta{width:calc(100% - 24px);grid-template-columns:1fr;text-align:center;padding:25px 18px}.cta-brand{display:none}.cta-copy{text-align:center}.cta-copy strong{font-size:19px}.cta-button{width:190px;margin:auto}.site-footer{width:calc(100% - 24px);font-size:9px}}
`

export default function Home(){
  return <main className="landing-page">
    <style>{uiStyles}</style>
    <header className="site-header">
      <div className="site-header-inner">
        <div className="header-brand"><div className="brand-lockup"><img src="/logo.png" alt="برمجها مع معاذ" className="brand-logo" /></div></div>
        <nav className="main-nav" aria-label="التنقل الرئيسي"><a className="active" href="#home">الرئيسية</a><a href="#courses">الكورسات</a><a href="#books">الكتب</a><a href="#stages">المراحل</a><a href="#about">عن المنصة</a></nav>
        <div className="header-actions"><span className="theme-toggle" aria-hidden="true"><span /></span><Link href="/login" className="header-login">تسجيل الدخول</Link><Link href="/register" className="header-register">إنشاء حساب</Link></div>
      </div>
    </header>

    <section id="home" className="hero-section"><div className="hero-inner">
      <div className="hero-copy"><div className="hero-badge">🎓 منصة تعليمية متكاملة لطلاب الثانوية العامة</div><h1>رحلتك للنجاح<br/><span>تبدأ من هنا</span></h1><p>مع برمجها مع معاذ هتتعلم بطريقة مختلفة.. شرح مبسط، محتوى احترافي، متابعة مستمرة، واختبارات شاملة تساعدك تحقق أعلى درجاتك.</p><div className="hero-buttons"><Link href="/register" className="hero-primary">ابدأ الآن <span>←</span></Link><a href="#stages" className="hero-secondary">استكشف المنصة</a></div><div className="hero-trust"><div className="trust-item"><div className="avatars"><i/><i/><i/></div><div><strong>+50,000</strong><small>طالب بيثقوا في المنصة</small></div></div><div className="trust-item rating"><strong>4.9</strong><span>★★★★★</span><small>تقييم الطلاب</small></div></div></div>
      <div className="hero-visual"><img src="/hero.png" alt="برمجها مع معاذ" className="hero-art" /></div>
    </div></section>

    <section id="courses" className="stages-section"><div className="stages-inner"><div className="stages-heading"><span>🎓 السنوات الدراسية</span><h2>اختر مرحلتك الدراسية</h2><p>ابدأ رحلتك التعليمية واكتشف المحتوى المناسب لصفك</p></div><div className="grade-cards">
      {grades.map((grade)=><Link href="/register" className={`grade-card tone-${grade.tone}`} key={grade.title}><div className="grade-cover"><img src="/hero.png" alt=""/><span className="grade-cover-label">{grade.label}</span></div><div className="grade-card-body"><div className="grade-icon"><Icon name={grade.icon}/></div><h3>{grade.title}</h3><p>دروس وكورسات واختبارات ومراجعات شاملة</p><b>اكتشف المحتوى ←</b></div></Link>)}
    </div></div></section>

    <section id="stages" className="platform-story"><div className="platform-story-inner">
      <div className="platform-story-visual"><img src="/hero.png" alt="منصة برمجها مع معاذ" className="platform-story-image"/><div className="platform-story-card"><div className="platform-story-card-icon"><Icon name="cap"/></div><div><strong>جاهز تبدأ رحلتك؟ 🚀</strong><small>تعلم • تابع • اختبر • اتطور</small></div></div></div>
      <div className="platform-story-copy"><span className="platform-story-badge">✨ منصة تعليمية متكاملة</span><h2>اتعلم صح مع <span>برمجها مع معاذ</span></h2><p>كل اللي تحتاجه عشان تبني أساس قوي وتحقق أفضل نتيجة. شرح واضح، كورسات منظمة، اختبارات ومراجعات، ومتابعة مستمرة تخليك عارف أنت فين وإيه الخطوة الجاية.</p><div className="story-points"><div className="story-point"><i><Icon name="video"/></i>شرح مبسط ومنظم</div><div className="story-point"><i><Icon name="check"/></i>اختبارات ومراجعات</div><div className="story-point"><i><Icon name="chart"/></i>متابعة مستوى الأداء</div><div className="story-point"><i><Icon name="headset"/></i>دعم مستمر للطلاب</div></div><div className="story-actions"><Link href="/register" className="story-primary">ابدأ رحلتك الآن ←</Link><a href="#about" className="story-secondary">اعرف أكتر <span>●</span></a></div></div>
    </div></section>

    <section className="stats-strip" aria-label="إحصائيات المنصة"><div><strong>+50,000</strong><span>طالب وطالبة</span><em><Icon name="users"/></em></div><div><strong>+150</strong><span>كورس تعليمي</span><em><Icon name="book"/></em></div><div><strong>+1,200</strong><span>ساعة شرح</span><em><Icon name="video"/></em></div><div><strong>+98%</strong><span>رضا الطلاب</span><em><Icon name="heart"/></em></div></section>

    <section id="about" className="why-section"><div className="why-heading"><h2>مميزات <span>المنصة</span></h2><p>كل الأدوات اللي تحتاجها عشان تتعلم بشكل أفضل وتوصل لهدفك</p></div><div className="features-grid">{features.map(([icon,title,desc])=><article className="feature-card" key={title}><div className="feature-icon"><Icon name={icon}/></div><h3>{title}</h3><p>{desc}</p></article>)}</div></section>

    <section className="bottom-cta" id="contact"><div className="cta-brand"><div className="brand-lockup"><img src="/logo.png" alt="برمجها مع معاذ" className="brand-logo"/></div></div><div className="cta-copy"><strong>مستقبلك يبدأ بقرار.. ابدأ دلوقتي</strong><span>انضم للمنصة وابدأ رحلتك نحو التفوق في الثانوية العامة</span></div><Link href="/register" className="cta-button">إنشاء حساب الآن ←</Link></section>
    <footer className="site-footer"><span>© برمجها معاذ 2026</span><span>الشروط • الخصوصية • الدعم</span></footer>
  </main>
}
