'use client'
import {ReactNode,useEffect,useState} from 'react';
import Link from 'next/link'; import {useRouter} from 'next/navigation';
import {LayoutDashboard,BookOpen,Wallet,Users,Settings,ShieldCheck,Globe,LogOut,Menu} from 'lucide-react'
const items=[['الرئيسية','/admin',LayoutDashboard],['الكورسات والفيديوهات','/admin/courses',BookOpen],['المدفوعات والحجوزات','/admin/payments',Wallet],['المستخدمون','/admin/users',Users],['الإعدادات','/admin/settings',Settings]] as const
export default function AdminShell({children}:{children:ReactNode}){
 const [open,setOpen]=useState(false); const [user,setUser]=useState<any>(null); const router=useRouter();
 useEffect(()=>{fetch('/api/auth/me').then(r=>r.ok?r.json():Promise.reject()).then(d=>{if(d.user?.role!=='ADMIN')throw new Error();setUser(d.user)}).catch(()=>router.replace('/login'))},[router]);
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});router.replace('/login')}
 return <main className="min-h-screen bg-[var(--bg)]"><header className="sticky top-0 z-30 bg-white/95 backdrop-blur border-b"><div className="container h-16 flex items-center justify-between"><button className="lg:hidden btn btn-soft" onClick={()=>setOpen(!open)}><Menu size={19}/></button><div className="brand-lockup"><img src="/brand-logo.png" className="w-20 h-11 object-cover rounded-xl"/><div><div className="font-black text-[var(--primary)]">لوحة إدارة Eng Moaaz Ismail</div><div className="text-xs muted flex items-center gap-2">{user?.name||'مدير النظام'}{user?.isSuperAdmin&&<span className="badge">SUPER ADMIN</span>}</div></div></div><button onClick={logout} className="btn btn-soft"><LogOut size={17}/> خروج</button></div></header><div className="container flex gap-6 py-6"><aside className={`${open?'block fixed inset-0 z-20 bg-white p-4 pt-20':'hidden'} lg:block w-64 shrink-0`}><div className="card p-3 lg:sticky lg:top-22">{items.map(([t,h,Icon])=><Link key={h} href={h} onClick={()=>setOpen(false)} className="flex items-center gap-3 rounded-xl px-4 py-3 hover:bg-[var(--primary-soft)] font-bold"><Icon size={18}/>{t}</Link>)}{user?.isSuperAdmin&&<><Link href="/admin/team" onClick={()=>setOpen(false)} className="flex items-center gap-3 rounded-xl px-4 py-3 hover:bg-[var(--primary-soft)] font-bold text-[var(--primary)]"><ShieldCheck size={18}/>المشرفون والصلاحيات</Link><Link href="/admin/website" onClick={()=>setOpen(false)} className="flex items-center gap-3 rounded-xl px-4 py-3 hover:bg-[var(--primary-soft)] font-bold text-[var(--primary)]"><Globe size={18}/>التحكم الكامل بالموقع</Link></>}</div></aside><section className="flex-1 min-w-0">{children}</section></div></main>}
