'use client'
import { ReactNode, useEffect, useState } from 'react'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { Bell, Home, BookOpen, ClipboardCheck, FileText, Library, CalendarCheck, BarChart3, User, MessageCircle, Menu, LogOut, X, LayoutDashboard } from 'lucide-react'
import { useStudentSession } from './StudentSessionProvider'

const items = [
  ['الرئيسية','/student',Home],['الكورسات','/student/courses',BookOpen],['الدروس','/student/lessons',FileText],['الامتحانات','/student/exams',ClipboardCheck],['الواجبات','/student/assignments',FileText],['الكتب','/student/books',Library],['الحضور','/student/attendance',CalendarCheck],['الدرجات','/student/grades',BarChart3],['التقارير','/student/analytics',BarChart3],['الإشعارات','/student/notifications',Bell],['الملف الشخصي','/student/profile',User],['الدعم','/student/support',MessageCircle],
] as const
const primaryNav=items.slice(0,4)
function roleTarget(role?:string){if(role==='ADMIN')return '/admin';if(role==='TEACHER')return '/teacher';if(role==='PARENT')return '/parent';if(role==='SUPPORT')return '/support';return '/student'}
function LoadingShell(){return <main className="student-shell student-loading-shell" aria-busy="true"><div className="student-header student-skeleton-header"><div className="student-header-inner"><div className="student-brand"><div className="student-skeleton student-skeleton-logo"/><div className="student-skeleton-copy"><div className="student-skeleton student-skeleton-name"/><div className="student-skeleton student-skeleton-sub"/></div></div><div className="student-skeleton-nav"><i/><i/><i/><i/></div><div className="student-actions"><div className="student-skeleton student-skeleton-btn"/><div className="student-skeleton student-skeleton-btn"/><div className="student-skeleton student-skeleton-avatar"/></div></div></div><div className="student-layout"><aside className="student-sidebar"><div className="student-sidebar-card student-skeleton-card"><div className="student-skeleton student-skeleton-title"/>{Array.from({length:8}).map((_,i)=><div key={i} className="student-skeleton student-skeleton-row"/>)}</div></aside><section className="student-content"><div className="student-skeleton student-skeleton-heading"/><div className="student-skeleton student-skeleton-text"/><div className="student-skeleton-grid">{Array.from({length:4}).map((_,i)=><div key={i} className="student-skeleton student-skeleton-stat"/>)}</div><div className="student-skeleton student-skeleton-panel"/></section></div><div className="student-loading-label"><span className="student-spinner"/>جاري تحميل حسابك...</div></main>}
export default function DashboardShell({children,title}:{children:ReactNode;title:string}){const {user,ready,logout}=useStudentSession();const [open,setOpen]=useState(false);const pathname=usePathname();useEffect(()=>setOpen(false),[pathname]);if(!ready)return <LoadingShell/>;if(!user)return null;return <main className="student-shell"><header className="student-header"><div className="student-header-inner"><Link className="student-brand" href="/student"><img src="/logo.png" alt="برمجها معاذ"/><div><strong>برمجها معاذ</strong><span>منصتك التعليمية</span></div></Link><nav className="student-top-nav" aria-label="التنقل الرئيسي">{primaryNav.map(([label,href])=><Link key={href} className={pathname===href?'active':''} href={href}>{label}</Link>)}</nav><div className="student-actions"><Link className="student-action" href="/"><Home size={16}/><span>الرئيسية</span></Link><Link className="student-action" href="/student/notifications"><Bell size={16}/><span>الإشعارات</span></Link><button className="student-menu-button" onClick={()=>setOpen(v=>!v)} aria-label="فتح القائمة">{open?<X size={18}/>:<Menu size={18}/>}</button><Link className="student-avatar" href="/student/profile" aria-label="الملف الشخصي">{user.name?.[0]||'ط'}</Link></div></div></header>{open&&<><button aria-label="إغلاق القائمة" className="fixed inset-0 z-[65] bg-black/15" onClick={()=>setOpen(false)}/><div className="student-mobile-menu">{items.map(([label,href,Icon])=><Link key={href} className={pathname===href?'active':''} href={href} onClick={()=>setOpen(false)}><Icon size={17}/>{label}</Link>)}<div className="mobile-divider"/><Link href="/" onClick={()=>setOpen(false)}><Home size={17}/> الصفحة الرئيسية</Link><Link href="/student/profile" onClick={()=>setOpen(false)}><User size={17}/> {user.name||'الملف الشخصي'}</Link><Link href={roleTarget(user.role)} onClick={()=>setOpen(false)}><LayoutDashboard size={17}/> لوحة الحساب</Link><button onClick={logout}><LogOut size={17}/> تسجيل الخروج</button></div></>}<div className="student-layout"><aside className="student-sidebar"><div className="student-sidebar-card"><div className="student-sidebar-title">{title}</div>{items.map(([label,href,Icon])=><Link key={href} className={pathname===href?'active':''} href={href}><Icon size={17}/>{label}</Link>)}</div></aside><section className="student-content">{children}</section></div><nav className="student-mobile-bar" aria-label="تنقل سريع">{primaryNav.map(([label,href,Icon])=><Link key={href} className={pathname===href?'active':''} href={href}><Icon size={17}/><span>{label}</span></Link>)}</nav></main>}
