'use client'

import { ReactNode, useEffect, useState } from 'react'
import Link from 'next/link'
import { usePathname, useRouter } from 'next/navigation'
import { Bell, Home, BookOpen, ClipboardCheck, FileText, Library, CalendarCheck, BarChart3, User, MessageCircle, Menu, LogOut, X, LayoutDashboard } from 'lucide-react'

const items = [
  ['الرئيسية','/student',Home],['الكورسات','/student/courses',BookOpen],['الدروس','/student/lessons',FileText],['الامتحانات','/student/exams',ClipboardCheck],['الواجبات','/student/assignments',FileText],['الكتب','/student/books',Library],['الحضور','/student/attendance',CalendarCheck],['الدرجات','/student/grades',BarChart3],['التقارير','/student/analytics',BarChart3],['الإشعارات','/student/notifications',Bell],['الملف الشخصي','/student/profile',User],['الدعم','/student/support',MessageCircle],
] as const

const primaryNav = items.slice(0,4)
function roleTarget(role?:string){if(role==='ADMIN')return '/admin';if(role==='TEACHER')return '/teacher';if(role==='PARENT')return '/parent';if(role==='SUPPORT')return '/support';return '/student'}
function LoadingShell(){return <main className="student-shell student-loading-shell" aria-busy="true"><header className="student-header"><div className="student-header-inner"><div className="student-brand"><div className="student-skeleton student-skeleton-logo"/><div><div className="student-skeleton student-skeleton-name"/><div className="student-skeleton student-skeleton-sub"/></div></div><div className="student-skeleton-nav"><i/><i/><i/><i/></div><div className="student-actions"><div className="student-skeleton student-skeleton-btn"/><div className="student-skeleton student-skeleton-avatar"/></div></div></header><div className="student-layout"><aside className="student-sidebar"><div className="student-sidebar-card"><div className="student-skeleton student-skeleton-title"/>{Array.from({length:8}).map((_,i)=><div className="student-skeleton student-skeleton-row" key={i}/>)}</div></aside><section className="student-content"><div className="student-skeleton student-skeleton-heading"/><div className="student-skeleton student-skeleton-text"/><div className="student-skeleton-grid">{Array.from({length:4}).map((_,i)=><div className="student-skeleton student-skeleton-stat" key={i}/>)}</div><div className="student-skeleton student-skeleton-panel"/></section></div><div className="student-loading-label"><span className="student-spinner"/>جاري تحميل حسابك...</div></main>}

export default function DashboardShell({children,title}:{children:ReactNode;title:string}){
  const [open,setOpen]=useState(false); const [user,setUser]=useState<{id?:string;name?:string;role?:string;phone?:string}|null>(null); const [checking,setChecking]=useState(true); const router=useRouter(); const pathname=usePathname()
  useEffect(()=>{let cancelled=false;fetch('/api/auth/me',{cache:'no-store'}).then(async r=>r.ok?r.json():null).then(d=>{if(cancelled)return;if(d?.user?.role!=='STUDENT')throw new Error('UNAUTHORIZED');setUser(d.user)}).catch(()=>{if(!cancelled)router.replace('/login')}).finally(()=>{if(!cancelled)setChecking(false)});return()=>{cancelled=true}},[router])
  useEffect(()=>setOpen(false),[pathname])
  async function logout(){await fetch('/api/auth/logout',{method:'POST'});router.replace('/login');router.refresh()}
  if(checking)return <LoadingShell/>; if(!user)return null
  return <>
    <style>{`
      .student-shell{min-height:100vh;background:linear-gradient(180deg,#fff 0%,#fbfaff 58%,#fff 100%);color:#24213a;padding-bottom:32px}
      .student-header{position:relative;z-index:60;height:76px;background:rgba(255,255,255,.98);border-bottom:1px solid #eee8f4;box-shadow:0 7px 24px rgba(42,24,65,.07);backdrop-filter:blur(10px)}
      .student-header-inner{height:100%;width:min(1360px,calc(100% - 32px));margin:auto;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:18px}
      .student-brand{display:flex;align-items:center;gap:10px;min-width:0}.student-brand img{width:46px;height:46px;object-fit:contain;border-radius:13px}.student-brand strong{display:block;color:#6d2fa3;font-size:16px;font-weight:950;white-space:nowrap}.student-brand span{display:block;color:#7b7385;font-size:10px;font-weight:800;margin-top:2px;white-space:nowrap}
      .student-top-nav{display:flex;align-items:center;justify-content:center;gap:6px}.student-top-nav a{height:42px;padding:0 14px;border-radius:12px;display:inline-flex;align-items:center;font-size:13px;font-weight:900;color:#30263d;white-space:nowrap}.student-top-nav a:hover,.student-top-nav a.active{background:#f3eafa;color:#6d2fa3}
      .student-actions{display:flex;align-items:center;justify-content:flex-end;gap:8px;min-width:0}.student-action{height:42px;border:1px solid #e7dfef;background:#fff;border-radius:12px;padding:0 13px;color:#30263d;display:inline-flex;align-items:center;gap:7px;font-size:12px;font-weight:900}.student-action:hover{border-color:#d3bee4;background:#faf6fd}.student-avatar{width:40px;height:40px;border-radius:50%;background:#f1e8fa;color:#6d2fa3;display:grid;place-items:center;font-weight:950;flex:0 0 40px}.student-menu-button{display:none}
      .student-layout{width:min(1360px,calc(100% - 32px));margin:auto;display:grid;grid-template-columns:250px minmax(0,1fr);gap:24px;padding:28px 0 0;direction:ltr}.student-sidebar{direction:rtl}.student-sidebar-card{background:#fff;border:1px solid #eee8f4;border-radius:22px;padding:12px;box-shadow:0 12px 30px rgba(42,24,65,.06)}.student-sidebar-title{padding:10px 12px 14px;border-bottom:1px solid #eee8f4;margin-bottom:8px;color:#6d2fa3;font-size:20px;font-weight:950}.student-sidebar a{display:flex;align-items:center;gap:10px;padding:11px 12px;border-radius:12px;color:#383043;font-size:13px;font-weight:850}.student-sidebar a:hover,.student-sidebar a.active{background:#f4ecfa;color:#6d2fa3}.student-content{direction:rtl;min-width:0}
      .student-mobile-menu,.student-mobile-bar{display:none}
      .student-loading-shell{min-height:100vh;position:relative;overflow:hidden}.student-skeleton{position:relative;overflow:hidden;background:#eee9f5;border-radius:12px}.student-skeleton:after{content:"";position:absolute;inset:0;transform:translateX(-100%);background:linear-gradient(90deg,transparent,rgba(255,255,255,.8),transparent);animation:studentShimmer 1.25s ease-in-out infinite}.student-skeleton-logo{width:46px;height:46px;border-radius:13px}.student-skeleton-name{width:132px;height:12px;margin-bottom:6px}.student-skeleton-sub{width:92px;height:8px}.student-skeleton-nav{display:flex;justify-content:center;gap:8px}.student-skeleton-nav i{display:block;width:72px;height:34px;border-radius:12px;background:#eee9f5}.student-skeleton-btn{width:82px;height:40px}.student-skeleton-avatar{width:40px;height:40px;border-radius:50%}.student-skeleton-title{width:120px;height:22px;margin:4px 10px 18px}.student-skeleton-row{height:38px;margin:7px 0}.student-skeleton-heading{width:310px;height:34px}.student-skeleton-text{width:480px;height:14px;margin-top:12px}.student-skeleton-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-top:26px}.student-skeleton-stat{height:108px}.student-skeleton-panel{height:180px;margin-top:18px}.student-loading-label{position:fixed;left:50%;bottom:24px;transform:translateX(-50%);display:inline-flex;align-items:center;gap:9px;background:#fff;border:1px solid #eee8f4;border-radius:999px;padding:10px 16px;box-shadow:0 10px 26px rgba(42,24,65,.09);color:#6d2fa3;font-size:12px;font-weight:900;z-index:100}.student-spinner{width:15px;height:15px;border:2px solid #eadcf4;border-top-color:#6d2fa3;border-radius:50%;animation:studentSpin .8s linear infinite}@keyframes studentShimmer{100%{transform:translateX(100%)}}@keyframes studentSpin{to{transform:rotate(360deg)}}
      @media(max-width:1050px){.student-header-inner{grid-template-columns:1fr auto}.student-top-nav{display:none}.student-menu-button{display:inline-flex;align-items:center;justify-content:center;width:42px;height:42px;border:1px solid #e7dfef;border-radius:12px;background:#fff;color:#6d2fa3}.student-layout{display:block;width:min(100%,calc(100% - 24px));padding-top:18px}.student-sidebar{display:none}.student-mobile-menu{position:fixed;top:88px;right:12px;left:12px;z-index:70;background:#fff;border:1px solid #eee8f4;border-radius:18px;box-shadow:0 18px 42px rgba(42,24,65,.14);padding:10px;display:flex;flex-direction:column;gap:3px;max-height:calc(100vh - 170px);overflow:auto}.student-mobile-menu a,.student-mobile-menu button{min-height:44px;padding:0 12px;border-radius:11px;display:flex;align-items:center;gap:10px;border:0;background:transparent;font:inherit;font-size:13px;font-weight:900;color:#383043;text-align:right}.student-mobile-menu a.active,.student-mobile-menu a:hover{background:#f4ecfa;color:#6d2fa3}.student-mobile-menu button{color:#b42318}.student-mobile-menu .mobile-divider{height:1px;background:#eee8f4;margin:5px 0}.student-mobile-bar{position:fixed;bottom:12px;left:12px;right:12px;z-index:80;background:rgba(255,255,255,.97);border:1px solid #eee8f4;border-radius:18px;box-shadow:0 12px 30px rgba(42,24,65,.13);display:grid;grid-template-columns:repeat(4,1fr);padding:7px}.student-mobile-bar a{display:grid;place-items:center;gap:4px;padding:7px 3px;border-radius:12px;font-size:10px;font-weight:900;color:#5e5668}.student-mobile-bar a.active{background:#f3eafa;color:#6d2fa3}.student-shell{padding-bottom:98px}.student-skeleton-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
      @media(max-width:560px){.student-header{height:66px}.student-header-inner{width:calc(100% - 14px);gap:6px}.student-brand img{width:40px;height:40px}.student-brand strong{font-size:14px}.student-brand span{display:none}.student-actions{gap:5px}.student-action{width:40px;height:40px;padding:0;justify-content:center}.student-action span{display:none}.student-avatar{width:38px;height:38px;flex-basis:38px}.student-layout{width:calc(100% - 14px)}.student-mobile-menu{top:75px;right:7px;left:7px}.student-skeleton-nav{display:none}.student-skeleton-btn{width:40px}.student-skeleton-grid{gap:9px}.student-skeleton-stat{height:90px}.student-skeleton-panel{height:120px}.student-loading-label{bottom:92px;font-size:11px;max-width:calc(100% - 24px);white-space:nowrap}}
    `}</style>
    <main className="student-shell">
      <header className="student-header"><div className="student-header-inner"><Link className="student-brand" href="/student"><img src="/logo.png" alt="برمجها معاذ"/><div><strong>برمجها معاذ</strong><span>منصتك التعليمية</span></div></Link><nav className="student-top-nav">{primaryNav.map(([label,href])=><Link key={href} className={pathname===href?'active':''} href={href}>{label}</Link>)}</nav><div className="student-actions"><Link className="student-action" href="/"><Home size={16}/><span>الرئيسية</span></Link><Link className="student-action" href="/student/notifications"><Bell size={16}/><span>الإشعارات</span></Link><button className="student-menu-button" onClick={()=>setOpen(v=>!v)} aria-label="القائمة">{open?<X size={18}/>:<Menu size={18}/>}</button><Link className="student-avatar" href="/student/profile">{user.name?.[0]||'ط'}</Link></div></div></header>
      {open&&<><button aria-label="إغلاق القائمة" className="fixed inset-0 z-[65] bg-black/15" onClick={()=>setOpen(false)}/><div className="student-mobile-menu">{items.map(([label,href,Icon])=><Link key={href} className={pathname===href?'active':''} href={href} onClick={()=>setOpen(false)}><Icon size={17}/>{label}</Link>)}<div className="mobile-divider"/><Link href="/" onClick={()=>setOpen(false)}><Home size={17}/> الصفحة الرئيسية</Link><Link href="/student/profile" onClick={()=>setOpen(false)}><User size={17}/> {user.name||'الملف الشخصي'}</Link><Link href={roleTarget(user.role)} onClick={()=>setOpen(false)}><LayoutDashboard size={17}/> لوحة الحساب</Link><button onClick={logout}><LogOut size={17}/> تسجيل الخروج</button></div></>}
      <div className="student-layout"><aside className="student-sidebar"><div className="student-sidebar-card"><div className="student-sidebar-title">{title}</div>{items.map(([label,href,Icon])=><Link key={href} className={pathname===href?'active':''} href={href}><Icon size={17}/>{label}</Link>)}</div></aside><section className="student-content">{children}</section></div>
      <nav className="student-mobile-bar">{primaryNav.map(([label,href,Icon])=><Link key={href} className={pathname===href?'active':''} href={href}><Icon size={17}/><span>{label}</span></Link>)}</nav>
    </main>
  </>
}
