'use client'
import DashboardShell from '@/components/DashboardShell'
import Link from 'next/link'
import {useEffect,useMemo,useState} from 'react'
import {ArrowRight,CheckCircle2,ClipboardPlus,Clock3,Plus,Trash2} from 'lucide-react'

const input='w-full rounded-2xl border border-[#e5dfed] bg-white px-4 py-3 text-sm font-semibold outline-none transition focus:border-[var(--primary)] focus:ring-4 focus:ring-[var(--primary-soft)]'
type Q={text:string;type:'MCQ';points:number;options:{text:string;isCorrect:boolean}[]}
const blank=():Q=>({text:'',type:'MCQ',points:1,options:[{text:'',isCorrect:true},{text:'',isCorrect:false},{text:'',isCorrect:false},{text:'',isCorrect:false}]})

export default function NewExam(){
 const [courses,setCourses]=useState<any[]>([]),[courseId,setCourseId]=useState(''),[title,setTitle]=useState(''),[duration,setDuration]=useState(30),[questions,setQuestions]=useState<Q[]>([blank()]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false)
 useEffect(()=>{fetch('/api/teacher/courses',{cache:'no-store'}).then(r=>r.json()).then(x=>setCourses(Array.isArray(x)?x:[]))},[])
 const course=useMemo(()=>courses.find(c=>c.id===courseId),[courses,courseId])
 function updateQ(i:number,patch:Partial<Q>){setQuestions(qs=>qs.map((q,n)=>n===i?{...q,...patch}:q))}
 function updateOption(qi:number,oi:number,text:string){setQuestions(qs=>qs.map((q,n)=>n===qi?{...q,options:q.options.map((o,j)=>j===oi?{...o,text}:o)}:q))}
 function correct(qi:number,oi:number){setQuestions(qs=>qs.map((q,n)=>n===qi?{...q,options:q.options.map((o,j)=>({...o,isCorrect:j===oi}))}:q))}
 function addQuestion(){setQuestions(q=>[...q,blank()])}
 async function submit(e:any){e.preventDefault();setBusy(true);setError('');setDone(false);try{const r=await fetch('/api/teacher/exams',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,durationMin:duration,courseId,questions})});const d=await r.json();if(!r.ok)throw Error(d.error);setDone(true);setTitle('');setQuestions([blank()])}catch(e:any){setError(e.message||'تعذر إنشاء الامتحان')}finally{setBusy(false)}}
 return <DashboardShell title="إنشاء امتحان"><div className="mx-auto w-full max-w-[1050px] space-y-5 pb-10">
  <Link href="/teacher/courses" className="inline-flex items-center gap-2 text-sm font-black text-[var(--primary)]"><ArrowRight size={17}/> الكورسات</Link>
  <section className="rounded-[30px] bg-[linear-gradient(135deg,#432067,#6d2fa3,#8d54bd)] p-7 text-white shadow-[0_18px_45px_rgba(109,47,163,.18)]"><div className="flex items-center gap-4"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-white/10"><ClipboardPlus size={24}/></div><div><h1 className="text-3xl font-black">إنشاء امتحان جديد</h1><p className="mt-1 text-sm font-medium text-white/75">أضف الأسئلة والاختيارات وحدد الإجابة الصحيحة، والطالب سيحصل على النتيجة فور التسليم.</p></div></div></section>
  {error&&<div className="rounded-2xl border border-red-100 bg-red-50 p-4 text-sm font-bold text-red-700">⚠️ {error}</div>}{done&&<div className="flex items-center gap-2 rounded-2xl border border-green-100 bg-green-50 p-4 text-sm font-bold text-green-700"><CheckCircle2 size={18}/> تم رفع الامتحان بنجاح وأصبح متاحًا لطلاب الكورس.</div>}
  <form onSubmit={submit} className="space-y-5"><section className="rounded-[26px] border border-[#eee8f4] bg-white p-5 shadow-[0_10px_30px_rgba(42,24,65,.05)]"><div className="grid gap-4 md:grid-cols-3"><div className="md:col-span-2"><label className="mb-2 block text-xs font-black text-[#77717e]">اسم الامتحان</label><input className={input} value={title} onChange={e=>setTitle(e.target.value)} placeholder="مثال: اختبار Unit 1" required/></div><div><label className="mb-2 block text-xs font-black text-[#77717e]">الكورس</label><select className={input} value={courseId} onChange={e=>setCourseId(e.target.value)} required><option value="">اختر الكورس</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></div><div><label className="mb-2 block text-xs font-black text-[#77717e]">مدة الامتحان بالدقائق</label><input className={input} type="number" min="1" max="300" value={duration} onChange={e=>setDuration(Number(e.target.value))}/></div></div></section>
  {questions.map((q,qi)=><section key={qi} className="rounded-[26px] border border-[#eee8f4] bg-white p-5 shadow-[0_10px_30px_rgba(42,24,65,.045)]"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#f3eafa] text-sm font-black text-[var(--primary)]">{qi+1}</span><h2 className="font-black">السؤال {qi+1}</h2></div>{questions.length>1&&<button type="button" onClick={()=>setQuestions(qs=>qs.filter((_,i)=>i!==qi))} className="rounded-xl bg-red-50 px-3 py-2 text-xs font-black text-red-700"><Trash2 size={15}/></button>}</div><textarea className={input+' mt-4 min-h-[100px] resize-none'} value={q.text} onChange={e=>updateQ(qi,{text:e.target.value})} placeholder="اكتب السؤال هنا..." required/><div className="mt-4 grid gap-3 sm:grid-cols-2">{q.options.map((o,oi)=><div key={oi} className={'rounded-2xl border p-3 '+(o.isCorrect?'border-green-300 bg-green-50':'border-[#eee8f4] bg-[#fcfbfe]')}><div className="flex items-center gap-2"><input type="radio" checked={o.isCorrect} onChange={()=>correct(qi,oi)}/><span className="text-xs font-black">{String.fromCharCode(65+oi)}</span><input className={input+' flex-1 py-2.5'} value={o.text} onChange={e=>updateOption(qi,oi,e.target.value)} placeholder={'الاختيار '+(oi+1)} required/></div><div className="mt-2 text-[10px] font-black text-green-700">{o.isCorrect?'✓ الإجابة الصحيحة':''}</div></div>)}</div></section>)}
  <div className="flex flex-wrap gap-3"><button type="button" onClick={addQuestion} className="inline-flex items-center gap-2 rounded-2xl border border-[#e5dfed] bg-white px-5 py-3.5 text-sm font-black text-[var(--primary)]"><Plus size={17}/> إضافة سؤال</button><button disabled={busy} className="inline-flex flex-1 items-center justify-center gap-2 rounded-2xl bg-[var(--primary)] px-6 py-3.5 text-sm font-black text-white shadow-lg disabled:opacity-50">{busy?'جاري رفع الامتحان...':'رفع الامتحان للطلاب'}</button></div></form>
 </div></DashboardShell>
}
