'use client'
import DashboardShell from '@/components/DashboardShell'; import {useEffect,useState} from 'react'
type Analytics={average:number;attendancePct:number;completedLessons:number;watchedPct:number;series:{date:string;value:number}[];gradeCount:number;examCount:number}
export default function Analytics(){
 const [d,setD]=useState<Analytics|null>(null); const [error,setError]=useState('')
 useEffect(()=>{fetch('/api/student/analytics',{cache:'no-store'}).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error||'تعذر تحميل التقرير');return x}).then(setD).catch(e=>setError(e.message||'تعذر تحميل التقرير'))},[])
 return <DashboardShell title="التقارير"><div className="mb-7"><h1 className="text-3xl font-black">تقرير أدائك</h1><p className="muted mt-2">أرقام مبنية على درجاتك وامتحاناتك وتقدمك الفعلي خلال الفترة الأخيرة.</p></div>
 {error?<div className="card p-8 text-center"><h2 className="font-black text-xl">تعذر تحميل التقرير</h2><p className="muted mt-2">{error}</p></div>:!d?<div className="card p-10 animate-pulse">جاري تحميل التقرير...</div>:<><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4"><div className="card p-5"><div className="muted text-sm">متوسط الدرجات</div><div className="text-3xl font-black text-[var(--primary)] mt-2">{d.average}%</div></div><div className="card p-5"><div className="muted text-sm">الحضور آخر 30 يوم</div><div className="text-3xl font-black text-[var(--primary)] mt-2">{d.attendancePct}%</div></div><div className="card p-5"><div className="muted text-sm">الدروس المكتملة</div><div className="text-3xl font-black text-[var(--primary)] mt-2">{d.completedLessons}</div></div><div className="card p-5"><div className="muted text-sm">متوسط المشاهدة</div><div className="text-3xl font-black text-[var(--primary)] mt-2">{d.watchedPct}%</div></div></div><div className="grid lg:grid-cols-2 gap-5 mt-6"><div className="card p-6"><div className="flex items-center justify-between"><h2 className="font-black text-xl">آخر قياسات الأداء</h2><span className="badge">{d.series.length} قياس</span></div>{d.series.length?<div className="h-56 flex items-end gap-2 mt-8">{d.series.map((p,i)=><div key={`${p.date}-${i}`} className="flex-1 min-w-0 flex flex-col justify-end items-center gap-2"><div className="w-full max-w-12 bg-[var(--primary-soft)] rounded-t-xl" style={{height:`${Math.max(12,p.value)}%`}} title={`${p.value}%`}/><span className="text-[10px] muted">{new Date(p.date).toLocaleDateString('ar-EG',{day:'numeric',month:'numeric'})}</span></div>)}</div>:<div className="muted mt-8">لسه مفيش بيانات كفاية لعرض التطور.</div>}</div><div className="card p-6"><h2 className="font-black text-xl">ملخص النشاط</h2><div className="space-y-3 mt-5"><div className="flex justify-between p-4 rounded-2xl bg-[var(--primary-soft)]"><span>الدرجات المسجلة</span><b>{d.gradeCount}</b></div><div className="flex justify-between p-4 rounded-2xl bg-[var(--primary-soft)]"><span>الامتحانات المسلّمة</span><b>{d.examCount}</b></div><div className="flex justify-between p-4 rounded-2xl bg-[var(--primary-soft)]"><span>متوسط المشاهدة</span><b>{d.watchedPct}%</b></div></div></div></div></>}
 </DashboardShell>
}
