import {NextResponse} from 'next/server'; import {db} from '@/lib/db'; import {requireRole} from '@/lib/auth';
export async function GET(){try{const u=await requireRole(['STUDENT']); if(!u.student)return NextResponse.json({error:'الحساب غير مكتمل'},{status:400}); const s=u.student.id; const [student,enrollments,progress,attempts,submissions,attendance,grades,notifications]=await Promise.all([
 db.student.findUnique({where:{id:s},include:{user:true,grade:true}}),
 db.courseEnrollment.findMany({where:{studentId:s},include:{course:{include:{subject:true,teacher:{include:{user:true}},modules:{include:{lessons:true}}}}}}),
 db.studentProgress.findMany({where:{studentId:s},include:{lesson:{include:{module:true}}}}),
 db.examAttempt.findMany({where:{studentId:s,submittedAt:{not:null}},orderBy:{submittedAt:'desc'},take:5,include:{exam:true}}),
 db.assignmentSubmission.findMany({where:{studentId:s},orderBy:{submittedAt:'desc'},take:5,include:{assignment:true}}),
 db.attendance.findMany({where:{studentId:s},orderBy:{date:'desc'},take:30}),
 db.studentGrade.findMany({where:{studentId:s},orderBy:{recordedAt:'desc'},take:8,include:{subject:true}}),
 db.notification.findMany({where:{userId:u.id},orderBy:{createdAt:'desc'},take:5})
 ]); const totalLessons=enrollments.reduce((n,e)=>n+e.course.modules.reduce((m,x)=>m+x.lessons.length,0),0); const done=progress.filter(p=>p.completed).length; const avg=grades.length?Math.round(grades.reduce((a,g)=>a+(g.score/g.maxScore)*100,0)/grades.length):0; const present=attendance.filter(a=>a.status==='PRESENT'||a.status==='ONLINE').length; const attendancePct=attendance.length?Math.round(present/attendance.length*100):0; const courses=enrollments.map(e=>{const ids=e.course.modules.flatMap(m=>m.lessons.map(l=>l.id)); const ps=progress.filter(p=>ids.includes(p.lessonId)); return {id:e.course.id,title:e.course.title,subject:e.course.subject.name,teacher:e.course.teacher.user.name,lessons:ids.length,progress:ids.length?Math.round(ps.reduce((a,p)=>a+p.watchedPct,0)/ids.length):0}}); return NextResponse.json({student:{name:student?.user.name,grade:student?.grade?.name},stats:{avg,attendance:attendancePct,courses:courses.length,lessonsCompleted:done,totalLessons},courses,continue:progress.filter(p=>!p.completed).sort((a,b)=>b.watchedPct-a.watchedPct).slice(0,1).map(p=>({lessonId:p.lessonId,title:p.lesson.title,course:p.lesson.module.title,watchedPct:p.watchedPct,lastPositionSec:p.lastPositionSec})),recentAttempts:attempts,recentSubmissions:submissions,grades,notifications})}catch(e){return NextResponse.json({error:'غير مصرح'},{status:401})}}
