'use client'
import DashboardShell from '@/components/DashboardShell'
import { useEffect,useRef,useState } from 'react'

type WalletData={balance:number;transactions:any[];recharges:any[]}
const methods=[['INSTAPAY','InstaPay'],['VODAFONE_CASH','Vodafone Cash'],['ETISALAT_CASH','Etisalat Cash'],['ORANGE_CASH','Orange Cash'],['BANK_TRANSFER','تحويل بنكي'],['OTHER','أخرى']]
const MAX_PROOF_BYTES=2*1024*1024
export default function WalletPage(){
 const [d,setD]=useState<WalletData>({balance:0,transactions:[],recharges:[]}); const [loading,setLoading]=useState(true); const [sending,setSending]=useState(false); const [refreshing,setRefreshing]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
 const [form,setForm]=useState({amount:'',method:'INSTAPAY',senderPhone:'',proof:null as File|null}); const proofRef=useRef<HTMLInputElement>(null)
 const load=async()=>{try{setError('');const r=await fetch('/api/student/wallet',{cache:'no-store'});const x=await r.json();if(!r.ok)throw new Error(x.error||'تعذر تحميل المحفظة');setD(x)}catch(e:any){setError(e.message)}finally{setLoading(false);setRefreshing(false)}}
 useEffect(()=>{load()},[])
 async function refresh(){setRefreshing(true);await load()}
 function chooseProof(file:File|null){setError('');if(!file){setForm(f=>({...f,proof:null}));return}if(!file.type.startsWith('image/')){setForm(f=>({...f,proof:null}));if(proofRef.current)proofRef.current.value='';setError('إثبات التحويل يجب أن يكون صورة');return}if(file.size>MAX_PROOF_BYTES){setForm(f=>({...f,proof:null}));if(proofRef.current)proofRef.current.value='';setError('حجم الصورة يجب ألا يتجاوز 2MB');return}setForm(f=>({...f,proof:file}))}
 async function recharge(e:any){e.preventDefault();setSending(true);setError('');setMessage('');try{if(!form.proof)throw new Error('ارفع صورة إثبات التحويل');const amount=Number(form.amount);if(!Number.isFinite(amount)||amount<=0)throw new Error('أدخل مبلغ شحن صحيح');if(!/^01\d{9}$/.test(form.senderPhone.trim()))throw new Error('أدخل رقم الهاتف المحول منه بشكل صحيح');const fd=new FormData();fd.append('amount',form.amount);fd.append('method',form.method);fd.append('senderPhone',form.senderPhone.trim());fd.append('proof',form.proof);const r=await fetch('/api/student/wallet/recharge',{method:'POST',body:fd});const x=await r.json();if(!r.ok)throw new Error(x.error||'تعذر إرسال الطلب');setMessage('تم إرسال طلب الشحن للمراجعة. سيظهر هنا فور تحديث الحالة.');setForm({amount:'',method:form.method,senderPhone:'',proof:null});if(proofRef.current)proofRef.current.value='';await load()}catch(e:any){setError(e.message)}finally{setSending(false)}}
 return <DashboardShell title="المحفظة"><div className="flex items-center justify-between gap-3 mb-7"><div><h1 className="text-3xl font-black">المحفظة</h1><p className="muted mt-2">اشحن رصيدك واشترِ الكورسات المتاحة لصفك مباشرة.</p></div><button type="button" onClick={refresh} disabled={loading||refreshing} className="btn btn-primary">{refreshing?'جاري التحديث...':'تحديث الرصيد'}</button></div>
 <div className="grid lg:grid-cols-[1fr_1.4fr] gap-5"><div className="card p-6"><div className="muted text-sm">الرصيد الحالي</div><div className="text-4xl font-black text-[var(--primary)] mt-2">{loading?'—':`${d.balance.toFixed(2)} ج.م`}</div><div className="mt-6 p-4 rounded-2xl bg-[var(--primary-soft)] text-sm leading-7">بعد قبول إثبات التحويل، الرصيد يضاف تلقائيًا للمحفظة ويمكن استخدامه لفتح المحتوى بشكل دائم.</div></div>
 <form onSubmit={recharge} className="card p-6 space-y-3"><h2 className="text-xl font-black">طلب شحن</h2><input required min="1" max="100000" step="0.01" type="number" className="w-full border rounded-xl p-3" placeholder="المبلغ بالجنيه" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><select className="w-full border rounded-xl p-3" value={form.method} onChange={e=>setForm({...form,method:e.target.value})}>{methods.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select><input required type="tel" inputMode="numeric" pattern="01[0-9]{9}" className="w-full border rounded-xl p-3" placeholder="رقم الهاتف المحول منه" value={form.senderPhone} onChange={e=>setForm({...form,senderPhone:e.target.value})}/><div><input ref={proofRef} required type="file" accept="image/*" className="w-full border rounded-xl p-3" onChange={e=>chooseProof(e.target.files?.[0]||null)}/><div className="muted text-xs mt-1">صورة فقط — الحد الأقصى 2MB.</div></div><button disabled={sending} className="btn btn-primary w-full">{sending?'جاري الإرسال...':'إرسال إثبات التحويل'}</button>{message&&<div className="p-3 rounded-xl bg-green-50 text-green-700 text-sm">{message}</div>}{error&&<div className="p-3 rounded-xl bg-red-50 text-red-700 text-sm">{error}</div>}</form></div>
 <div className="grid lg:grid-cols-2 gap-5 mt-6"><div className="card p-6"><h2 className="text-xl font-black mb-4">طلبات الشحن</h2><div className="space-y-3">{d.recharges.map(r=><div key={r.id} className="p-4 rounded-2xl border flex items-center justify-between gap-3"><div><b>{r.amount} ج.م</b><div className="muted text-xs mt-1">{new Date(r.createdAt).toLocaleString('ar-EG')}</div></div><span className="badge">{r.status==='APPROVED'?'مقبول':r.status==='REJECTED'?'مرفوض':'قيد المراجعة'}</span></div>)}{!d.recharges.length&&<div className="muted">لا توجد طلبات شحن.</div>}</div></div><div className="card p-6"><h2 className="text-xl font-black mb-4">حركة المحفظة</h2><div className="space-y-3">{d.transactions.map(t=><div key={t.id} className="p-4 rounded-2xl border flex items-center justify-between gap-3"><div><b>{t.description}</b><div className="muted text-xs mt-1">{new Date(t.createdAt).toLocaleString('ar-EG')}</div></div><div className={Number(t.amount)>=0?'text-green-600':'text-red-600'}>{Number(t.amount)>=0?'+':''}{Number(t.amount).toFixed(2)} ج.م</div></div>)}{!d.transactions.length&&<div className="muted">لا توجد حركات حتى الآن.</div>}</div></div></div></DashboardShell>
}
